//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use core::ptr::NonNull;
use objc2::__framework_prelude::*;
use objc2_foundation::*;

use crate::*;

extern_class!(
    /// An MXDiagnostic subclass that encapsulates CPU exception diagnostic reports.
    ///
    /// CPU exceptions occur when your application consumes excessive CPU time in a short period of time.
    ///
    /// CPU exceptions can be both fatal and non-fatal to your application.
    ///
    /// See also [Apple's documentation](https://developer.apple.com/documentation/metrickit/mxcpuexceptiondiagnostic?language=objc)
    #[unsafe(super(MXDiagnostic, NSObject))]
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(feature = "MXDiagnostic")]
    pub struct MXCPUExceptionDiagnostic;
);

#[cfg(feature = "MXDiagnostic")]
unsafe impl NSCoding for MXCPUExceptionDiagnostic {}

#[cfg(feature = "MXDiagnostic")]
unsafe impl NSObjectProtocol for MXCPUExceptionDiagnostic {}

#[cfg(feature = "MXDiagnostic")]
unsafe impl NSSecureCoding for MXCPUExceptionDiagnostic {}

#[cfg(feature = "MXDiagnostic")]
impl MXCPUExceptionDiagnostic {
    extern_methods!(
        #[cfg(feature = "MXCallStackTree")]
        /// The application call stack tree associated with the excessive CPU consumption.
        #[unsafe(method(callStackTree))]
        #[unsafe(method_family = none)]
        pub unsafe fn callStackTree(&self) -> Retained<MXCallStackTree>;

        /// Total CPU time consumed in the scope of this CPU exception.
        ///
        /// Dimensioned as NSUnitDuration.
        #[unsafe(method(totalCPUTime))]
        #[unsafe(method_family = none)]
        pub unsafe fn totalCPUTime(&self) -> Retained<NSMeasurement<NSUnitDuration>>;

        /// Total time that the application was sampled for during the CPU exception.
        ///
        /// Dimensioned as NSUnitDuration.
        #[unsafe(method(totalSampledTime))]
        #[unsafe(method_family = none)]
        pub unsafe fn totalSampledTime(&self) -> Retained<NSMeasurement<NSUnitDuration>>;
    );
}

/// Methods declared on superclass `NSObject`.
#[cfg(feature = "MXDiagnostic")]
impl MXCPUExceptionDiagnostic {
    extern_methods!(
        #[unsafe(method(init))]
        #[unsafe(method_family = init)]
        pub unsafe fn init(this: Allocated<Self>) -> Retained<Self>;

        #[unsafe(method(new))]
        #[unsafe(method_family = new)]
        pub unsafe fn new() -> Retained<Self>;
    );
}
