//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use core::ffi::*;
use core::ptr::NonNull;
use objc2::__framework_prelude::*;
use objc2_foundation::*;

use crate::*;

extern_class!(
    /// [Apple's documentation](https://developer.apple.com/documentation/corelocation/clbeaconregion?language=objc)
    #[unsafe(super(CLRegion, NSObject))]
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(feature = "CLRegion")]
    #[deprecated]
    pub struct CLBeaconRegion;
);

#[cfg(feature = "CLRegion")]
unsafe impl NSCoding for CLBeaconRegion {}

#[cfg(feature = "CLRegion")]
unsafe impl NSCopying for CLBeaconRegion {}

#[cfg(feature = "CLRegion")]
unsafe impl CopyingHelper for CLBeaconRegion {
    type Result = Self;
}

#[cfg(feature = "CLRegion")]
unsafe impl NSObjectProtocol for CLBeaconRegion {}

#[cfg(feature = "CLRegion")]
unsafe impl NSSecureCoding for CLBeaconRegion {}

extern_methods!(
    #[cfg(feature = "CLRegion")]
    unsafe impl CLBeaconRegion {
        #[method(initWithUUID:identifier:)]
        #[unsafe(method_family = init)]
        pub unsafe fn initWithUUID_identifier(
            this: Allocated<Self>,
            uuid: &NSUUID,
            identifier: &NSString,
        ) -> Retained<Self>;

        #[deprecated]
        #[method(initWithProximityUUID:identifier:)]
        #[unsafe(method_family = init)]
        pub unsafe fn initWithProximityUUID_identifier(
            this: Allocated<Self>,
            proximity_uuid: &NSUUID,
            identifier: &NSString,
        ) -> Retained<Self>;

        #[cfg(feature = "CLBeaconIdentityCondition")]
        #[method(initWithUUID:major:identifier:)]
        #[unsafe(method_family = init)]
        pub unsafe fn initWithUUID_major_identifier(
            this: Allocated<Self>,
            uuid: &NSUUID,
            major: CLBeaconMajorValue,
            identifier: &NSString,
        ) -> Retained<Self>;

        #[cfg(feature = "CLBeaconIdentityCondition")]
        #[deprecated]
        #[method(initWithProximityUUID:major:identifier:)]
        #[unsafe(method_family = init)]
        pub unsafe fn initWithProximityUUID_major_identifier(
            this: Allocated<Self>,
            proximity_uuid: &NSUUID,
            major: CLBeaconMajorValue,
            identifier: &NSString,
        ) -> Retained<Self>;

        #[cfg(feature = "CLBeaconIdentityCondition")]
        #[method(initWithUUID:major:minor:identifier:)]
        #[unsafe(method_family = init)]
        pub unsafe fn initWithUUID_major_minor_identifier(
            this: Allocated<Self>,
            uuid: &NSUUID,
            major: CLBeaconMajorValue,
            minor: CLBeaconMinorValue,
            identifier: &NSString,
        ) -> Retained<Self>;

        #[cfg(feature = "CLBeaconIdentityCondition")]
        #[deprecated]
        #[method(initWithProximityUUID:major:minor:identifier:)]
        #[unsafe(method_family = init)]
        pub unsafe fn initWithProximityUUID_major_minor_identifier(
            this: Allocated<Self>,
            proximity_uuid: &NSUUID,
            major: CLBeaconMajorValue,
            minor: CLBeaconMinorValue,
            identifier: &NSString,
        ) -> Retained<Self>;

        #[cfg(all(
            feature = "CLBeaconIdentityCondition",
            feature = "CLBeaconIdentityConstraint",
            feature = "CLCondition"
        ))]
        #[method(initWithBeaconIdentityConstraint:identifier:)]
        #[unsafe(method_family = init)]
        pub unsafe fn initWithBeaconIdentityConstraint_identifier(
            this: Allocated<Self>,
            beacon_identity_constraint: &CLBeaconIdentityConstraint,
            identifier: &NSString,
        ) -> Retained<Self>;

        #[deprecated]
        #[method(peripheralDataWithMeasuredPower:)]
        #[unsafe(method_family = none)]
        pub unsafe fn peripheralDataWithMeasuredPower(
            &self,
            measured_power: Option<&NSNumber>,
        ) -> Retained<NSMutableDictionary<NSString, AnyObject>>;

        #[cfg(all(
            feature = "CLBeaconIdentityCondition",
            feature = "CLBeaconIdentityConstraint",
            feature = "CLCondition"
        ))]
        #[method(beaconIdentityConstraint)]
        #[unsafe(method_family = none)]
        pub unsafe fn beaconIdentityConstraint(&self) -> Retained<CLBeaconIdentityConstraint>;

        #[method(UUID)]
        #[unsafe(method_family = none)]
        pub unsafe fn UUID(&self) -> Retained<NSUUID>;

        #[deprecated]
        #[method(proximityUUID)]
        #[unsafe(method_family = none)]
        pub unsafe fn proximityUUID(&self) -> Retained<NSUUID>;

        #[deprecated]
        #[method(major)]
        #[unsafe(method_family = none)]
        pub unsafe fn major(&self) -> Option<Retained<NSNumber>>;

        #[deprecated]
        #[method(minor)]
        #[unsafe(method_family = none)]
        pub unsafe fn minor(&self) -> Option<Retained<NSNumber>>;

        #[deprecated]
        #[method(notifyEntryStateOnDisplay)]
        #[unsafe(method_family = none)]
        pub unsafe fn notifyEntryStateOnDisplay(&self) -> bool;

        /// Setter for [`notifyEntryStateOnDisplay`][Self::notifyEntryStateOnDisplay].
        #[deprecated]
        #[method(setNotifyEntryStateOnDisplay:)]
        #[unsafe(method_family = none)]
        pub unsafe fn setNotifyEntryStateOnDisplay(&self, notify_entry_state_on_display: bool);
    }
);

extern_methods!(
    /// Methods declared on superclass `CLRegion`
    #[cfg(feature = "CLRegion")]
    unsafe impl CLBeaconRegion {
        #[cfg(feature = "CLLocation")]
        #[deprecated = "Please see CLCircularRegion"]
        #[method(initCircularRegionWithCenter:radius:identifier:)]
        #[unsafe(method_family = init)]
        pub unsafe fn initCircularRegionWithCenter_radius_identifier(
            this: Allocated<Self>,
            center: CLLocationCoordinate2D,
            radius: CLLocationDistance,
            identifier: &NSString,
        ) -> Retained<Self>;
    }
);

extern_methods!(
    /// Methods declared on superclass `NSObject`
    #[cfg(feature = "CLRegion")]
    unsafe impl CLBeaconRegion {
        #[method(init)]
        #[unsafe(method_family = init)]
        pub unsafe fn init(this: Allocated<Self>) -> Retained<Self>;

        #[method(new)]
        #[unsafe(method_family = new)]
        pub unsafe fn new() -> Retained<Self>;
    }
);

extern_class!(
    /// [Apple's documentation](https://developer.apple.com/documentation/corelocation/clbeacon?language=objc)
    #[unsafe(super(NSObject))]
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub struct CLBeacon;
);

unsafe impl NSCoding for CLBeacon {}

unsafe impl NSCopying for CLBeacon {}

unsafe impl CopyingHelper for CLBeacon {
    type Result = Self;
}

unsafe impl NSObjectProtocol for CLBeacon {}

unsafe impl NSSecureCoding for CLBeacon {}

extern_methods!(
    unsafe impl CLBeacon {
        #[method(timestamp)]
        #[unsafe(method_family = none)]
        pub unsafe fn timestamp(&self) -> Retained<NSDate>;

        #[method(UUID)]
        #[unsafe(method_family = none)]
        pub unsafe fn UUID(&self) -> Retained<NSUUID>;

        #[deprecated]
        #[method(proximityUUID)]
        #[unsafe(method_family = none)]
        pub unsafe fn proximityUUID(&self) -> Retained<NSUUID>;

        #[method(major)]
        #[unsafe(method_family = none)]
        pub unsafe fn major(&self) -> Retained<NSNumber>;

        #[method(minor)]
        #[unsafe(method_family = none)]
        pub unsafe fn minor(&self) -> Retained<NSNumber>;

        #[cfg(feature = "CLRegion")]
        #[method(proximity)]
        #[unsafe(method_family = none)]
        pub unsafe fn proximity(&self) -> CLProximity;

        #[cfg(feature = "CLLocation")]
        #[method(accuracy)]
        #[unsafe(method_family = none)]
        pub unsafe fn accuracy(&self) -> CLLocationAccuracy;

        #[method(rssi)]
        #[unsafe(method_family = none)]
        pub unsafe fn rssi(&self) -> NSInteger;
    }
);

extern_methods!(
    /// Methods declared on superclass `NSObject`
    unsafe impl CLBeacon {
        #[method(init)]
        #[unsafe(method_family = init)]
        pub unsafe fn init(this: Allocated<Self>) -> Retained<Self>;

        #[method(new)]
        #[unsafe(method_family = new)]
        pub unsafe fn new() -> Retained<Self>;
    }
);
