//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use objc2::__framework_prelude::*;
use objc2_foundation::*;

use crate::*;

/// [Apple's documentation](https://developer.apple.com/documentation/mapkit/mkmaptype?language=objc)
// NS_ENUM
#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct MKMapType(pub NSUInteger);
impl MKMapType {
    #[doc(alias = "MKMapTypeStandard")]
    pub const Standard: Self = Self(0);
    #[doc(alias = "MKMapTypeSatellite")]
    pub const Satellite: Self = Self(1);
    #[doc(alias = "MKMapTypeHybrid")]
    pub const Hybrid: Self = Self(2);
    #[doc(alias = "MKMapTypeSatelliteFlyover")]
    pub const SatelliteFlyover: Self = Self(3);
    #[doc(alias = "MKMapTypeHybridFlyover")]
    pub const HybridFlyover: Self = Self(4);
    #[doc(alias = "MKMapTypeMutedStandard")]
    pub const MutedStandard: Self = Self(5);
}

unsafe impl Encode for MKMapType {
    const ENCODING: Encoding = NSUInteger::ENCODING;
}

unsafe impl RefEncode for MKMapType {
    const ENCODING_REF: Encoding = Encoding::Pointer(&Self::ENCODING);
}

extern "C" {
    /// [Apple's documentation](https://developer.apple.com/documentation/mapkit/mkerrordomain?language=objc)
    pub static MKErrorDomain: &'static NSString;
}

/// [Apple's documentation](https://developer.apple.com/documentation/mapkit/mkerrorcode?language=objc)
// NS_ENUM
#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct MKErrorCode(pub NSUInteger);
impl MKErrorCode {
    pub const MKErrorUnknown: Self = Self(1);
    pub const MKErrorServerFailure: Self = Self(2);
    pub const MKErrorLoadingThrottled: Self = Self(3);
    pub const MKErrorPlacemarkNotFound: Self = Self(4);
    pub const MKErrorDirectionsNotFound: Self = Self(5);
    pub const MKErrorDecodingFailed: Self = Self(6);
}

unsafe impl Encode for MKErrorCode {
    const ENCODING: Encoding = NSUInteger::ENCODING;
}

unsafe impl RefEncode for MKErrorCode {
    const ENCODING_REF: Encoding = Encoding::Pointer(&Self::ENCODING);
}

/// [Apple's documentation](https://developer.apple.com/documentation/mapkit/mkfeaturevisibility?language=objc)
// NS_ENUM
#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct MKFeatureVisibility(pub NSInteger);
impl MKFeatureVisibility {
    #[doc(alias = "MKFeatureVisibilityAdaptive")]
    pub const Adaptive: Self = Self(0);
    #[doc(alias = "MKFeatureVisibilityHidden")]
    pub const Hidden: Self = Self(1);
    #[doc(alias = "MKFeatureVisibilityVisible")]
    pub const Visible: Self = Self(2);
}

unsafe impl Encode for MKFeatureVisibility {
    const ENCODING: Encoding = NSInteger::ENCODING;
}

unsafe impl RefEncode for MKFeatureVisibility {
    const ENCODING_REF: Encoding = Encoding::Pointer(&Self::ENCODING);
}

/// [Apple's documentation](https://developer.apple.com/documentation/mapkit/mklocalsearchregionpriority?language=objc)
// NS_ENUM
#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct MKLocalSearchRegionPriority(pub NSInteger);
impl MKLocalSearchRegionPriority {
    #[doc(alias = "MKLocalSearchRegionPriorityDefault")]
    pub const Default: Self = Self(0);
    #[doc(alias = "MKLocalSearchRegionPriorityRequired")]
    pub const Required: Self = Self(1);
}

unsafe impl Encode for MKLocalSearchRegionPriority {
    const ENCODING: Encoding = NSInteger::ENCODING;
}

unsafe impl RefEncode for MKLocalSearchRegionPriority {
    const ENCODING_REF: Encoding = Encoding::Pointer(&Self::ENCODING);
}
