//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use core::ffi::*;
use core::ptr::NonNull;
use objc2::__framework_prelude::*;
#[cfg(feature = "objc2-core-location")]
use objc2_core_location::*;
use objc2_foundation::*;

use crate::*;

extern_class!(
    /// [Apple's documentation](https://developer.apple.com/documentation/mapkit/mkuserlocation?language=objc)
    #[unsafe(super(NSObject))]
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub struct MKUserLocation;
);

#[cfg(feature = "MKAnnotation")]
unsafe impl MKAnnotation for MKUserLocation {}

unsafe impl NSObjectProtocol for MKUserLocation {}

extern_methods!(
    unsafe impl MKUserLocation {
        #[method(isUpdating)]
        pub unsafe fn isUpdating(&self) -> bool;

        #[cfg(feature = "objc2-core-location")]
        #[unsafe(method_family(none))]
        #[method_id(location)]
        pub unsafe fn location(&self) -> Option<Retained<CLLocation>>;

        #[cfg(feature = "objc2-core-location")]
        #[unsafe(method_family(none))]
        #[method_id(heading)]
        pub unsafe fn heading(&self) -> Option<Retained<CLHeading>>;

        #[unsafe(method_family(none))]
        #[method_id(title)]
        pub unsafe fn title(&self) -> Option<Retained<NSString>>;

        /// Setter for [`title`][Self::title].
        #[method(setTitle:)]
        pub unsafe fn setTitle(&self, title: Option<&NSString>);

        #[unsafe(method_family(none))]
        #[method_id(subtitle)]
        pub unsafe fn subtitle(&self) -> Option<Retained<NSString>>;

        /// Setter for [`subtitle`][Self::subtitle].
        #[method(setSubtitle:)]
        pub unsafe fn setSubtitle(&self, subtitle: Option<&NSString>);
    }
);

extern_methods!(
    /// Methods declared on superclass `NSObject`
    unsafe impl MKUserLocation {
        #[unsafe(method_family(init))]
        #[method_id(init)]
        pub unsafe fn init(this: Allocated<Self>) -> Retained<Self>;

        #[unsafe(method_family(new))]
        #[method_id(new)]
        pub unsafe fn new() -> Retained<Self>;
    }
);
