//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use core::ffi::*;
use core::ptr::NonNull;
use objc2::__framework_prelude::*;
use objc2_foundation::*;
use objc2_metal::*;

use crate::*;

extern_class!(
    /// A filter that returns a specified value for each pixel with a value greater than a specified threshold or 0 otherwise.
    ///
    /// ## Overview
    ///
    /// An [`MPSImageThresholdBinary`](https://developer.apple.com/documentation/metalperformanceshaders/mpsimagethresholdbinary) filter converts a single channel image to a binary image. If the input image is not a single channel image, the function first converts the input image into a single channel luminance image using the linear gray color transform, and then it applies the threshold.
    ///
    /// The following listing shows the threshold binary function.
    ///
    /// Listing 1. Threshold binary function
    ///
    /// ```other
    /// destinationPixelValue = sourcePixelValue > thresholdValue ? maximumValue : 0
    /// ```
    ///
    ///
    /// The MPSThreshold filter applies a fixed-level threshold to each pixel in the image.
    /// The threshold functions convert a single channel image to a binary image.
    /// If the input image is not a single channel image, convert the inputimage to a single channel
    /// luminance image using the linearGrayColorTransform and then apply the threshold.
    /// The ThresholdBinary function is:
    /// destinationPixelValue = sourcePixelValue > thresholdValue ? maximumValue : 0
    #[unsafe(super(MPSUnaryImageKernel, MPSKernel, NSObject))]
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(all(feature = "MPSCore", feature = "MPSImageKernel", feature = "MPSKernel"))]
    pub struct MPSImageThresholdBinary;
);

#[cfg(all(feature = "MPSCore", feature = "MPSImageKernel", feature = "MPSKernel"))]
extern_conformance!(
    unsafe impl NSCoding for MPSImageThresholdBinary {}
);

#[cfg(all(feature = "MPSCore", feature = "MPSImageKernel", feature = "MPSKernel"))]
extern_conformance!(
    unsafe impl NSCopying for MPSImageThresholdBinary {}
);

#[cfg(all(feature = "MPSCore", feature = "MPSImageKernel", feature = "MPSKernel"))]
unsafe impl CopyingHelper for MPSImageThresholdBinary {
    type Result = Self;
}

#[cfg(all(feature = "MPSCore", feature = "MPSImageKernel", feature = "MPSKernel"))]
extern_conformance!(
    unsafe impl NSObjectProtocol for MPSImageThresholdBinary {}
);

#[cfg(all(feature = "MPSCore", feature = "MPSImageKernel", feature = "MPSKernel"))]
extern_conformance!(
    unsafe impl NSSecureCoding for MPSImageThresholdBinary {}
);

#[cfg(all(feature = "MPSCore", feature = "MPSImageKernel", feature = "MPSKernel"))]
impl MPSImageThresholdBinary {
    extern_methods!(
        /// initialize a MPSImageThresholdBinary filter
        ///
        /// Parameter `device`: The device the filter will run on
        ///
        /// Parameter `thresholdValue`: The threshold value to use
        ///
        /// Parameter `maximumValue`: The maximum value to use
        ///
        /// Parameter `transform`: This matrix is an array of 3 floats.
        /// The default if no transform is specifed is BT.601/JPEG: {0.299f, 0.587f, 0.114f};
        ///
        /// # Safety
        ///
        /// `transform` must be a valid pointer or null.
        #[unsafe(method(initWithDevice:thresholdValue:maximumValue:linearGrayColorTransform:))]
        #[unsafe(method_family = init)]
        pub unsafe fn initWithDevice_thresholdValue_maximumValue_linearGrayColorTransform(
            this: Allocated<Self>,
            device: &ProtocolObject<dyn MTLDevice>,
            threshold_value: c_float,
            maximum_value: c_float,
            transform: *const c_float,
        ) -> Retained<Self>;

        /// NSSecureCoding compatability
        ///
        /// While the standard NSSecureCoding/NSCoding method
        /// -initWithCoder: should work, since the file can't
        /// know which device your data is allocated on, we
        /// have to guess and may guess incorrectly.  To avoid
        /// that problem, use initWithCoder:device instead.
        ///
        /// Parameter `aDecoder`: The NSCoder subclass with your serialized MPSKernel
        ///
        /// Parameter `device`: The MTLDevice on which to make the MPSKernel
        ///
        /// Returns: A new MPSKernel object, or nil if failure.
        ///
        /// # Safety
        ///
        /// `a_decoder` possibly has further requirements.
        #[unsafe(method(initWithCoder:device:))]
        #[unsafe(method_family = init)]
        pub unsafe fn initWithCoder_device(
            this: Allocated<Self>,
            a_decoder: &NSCoder,
            device: &ProtocolObject<dyn MTLDevice>,
        ) -> Option<Retained<Self>>;

        #[unsafe(method(initWithDevice:))]
        #[unsafe(method_family = init)]
        pub unsafe fn initWithDevice(
            this: Allocated<Self>,
            device: &ProtocolObject<dyn MTLDevice>,
        ) -> Retained<Self>;

        /// The threshold value used to init the threshold filter
        #[unsafe(method(thresholdValue))]
        #[unsafe(method_family = none)]
        pub unsafe fn thresholdValue(&self) -> c_float;

        /// The maximum value used to init the threshold filter
        #[unsafe(method(maximumValue))]
        #[unsafe(method_family = none)]
        pub unsafe fn maximumValue(&self) -> c_float;

        /// The color transform used to init the threshold filter
        #[unsafe(method(transform))]
        #[unsafe(method_family = none)]
        pub unsafe fn transform(&self) -> NonNull<c_float>;
    );
}

/// Methods declared on superclass `MPSKernel`.
#[cfg(all(feature = "MPSCore", feature = "MPSImageKernel", feature = "MPSKernel"))]
impl MPSImageThresholdBinary {
    extern_methods!(
        /// Called by NSCoder to decode MPSKernels
        ///
        /// This isn't the right interface to decode a MPSKernel, but
        /// it is the one that NSCoder uses. To enable your NSCoder
        /// (e.g. NSKeyedUnarchiver) to set which device to use
        /// extend the object to adopt the MPSDeviceProvider
        /// protocol. Otherwise, the Metal system default device
        /// will be used.
        ///
        /// # Safety
        ///
        /// `a_decoder` possibly has further requirements.
        #[unsafe(method(initWithCoder:))]
        #[unsafe(method_family = init)]
        pub unsafe fn initWithCoder(
            this: Allocated<Self>,
            a_decoder: &NSCoder,
        ) -> Option<Retained<Self>>;
    );
}

/// Methods declared on superclass `NSObject`.
#[cfg(all(feature = "MPSCore", feature = "MPSImageKernel", feature = "MPSKernel"))]
impl MPSImageThresholdBinary {
    extern_methods!(
        #[unsafe(method(init))]
        #[unsafe(method_family = init)]
        pub unsafe fn init(this: Allocated<Self>) -> Retained<Self>;

        #[unsafe(method(new))]
        #[unsafe(method_family = new)]
        pub unsafe fn new() -> Retained<Self>;
    );
}

extern_class!(
    /// A filter that returns 0 for each pixel with a value greater than a specified threshold or a specified value otherwise.
    ///
    /// ## Overview
    ///
    /// An [`MPSImageThresholdBinaryInverse`](https://developer.apple.com/documentation/metalperformanceshaders/mpsimagethresholdbinaryinverse) function converts a single channel image to a binary image. If the input image is not a single channel image, the function first converts the input image into a single channel luminance image using the linear gray color transform, and then it applies the threshold. The following listing shows the threshold binary inverse function.
    ///
    /// Listing 1. Threshold binary inverse function
    ///
    /// ```other
    /// destinationPixelValue = sourcePixelValue > thresholdValue ? 0 : maximumValue
    /// ```
    ///
    ///
    /// The MPSImageThresholdBinaryInverse filter applies a fixed-level threshold to each pixel in the image.
    /// The threshold functions convert a single channel image to a binary image.
    /// If the input image is not a single channel image, convert the inputimage to a single channel
    /// luminance image using the linearGrayColorTransform and then apply the threshold.
    /// The ThresholdBinaryInverse function is:
    /// destinationPixelValue = sourcePixelValue > thresholdValue ? 0 : maximumValue
    #[unsafe(super(MPSUnaryImageKernel, MPSKernel, NSObject))]
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(all(feature = "MPSCore", feature = "MPSImageKernel", feature = "MPSKernel"))]
    pub struct MPSImageThresholdBinaryInverse;
);

#[cfg(all(feature = "MPSCore", feature = "MPSImageKernel", feature = "MPSKernel"))]
extern_conformance!(
    unsafe impl NSCoding for MPSImageThresholdBinaryInverse {}
);

#[cfg(all(feature = "MPSCore", feature = "MPSImageKernel", feature = "MPSKernel"))]
extern_conformance!(
    unsafe impl NSCopying for MPSImageThresholdBinaryInverse {}
);

#[cfg(all(feature = "MPSCore", feature = "MPSImageKernel", feature = "MPSKernel"))]
unsafe impl CopyingHelper for MPSImageThresholdBinaryInverse {
    type Result = Self;
}

#[cfg(all(feature = "MPSCore", feature = "MPSImageKernel", feature = "MPSKernel"))]
extern_conformance!(
    unsafe impl NSObjectProtocol for MPSImageThresholdBinaryInverse {}
);

#[cfg(all(feature = "MPSCore", feature = "MPSImageKernel", feature = "MPSKernel"))]
extern_conformance!(
    unsafe impl NSSecureCoding for MPSImageThresholdBinaryInverse {}
);

#[cfg(all(feature = "MPSCore", feature = "MPSImageKernel", feature = "MPSKernel"))]
impl MPSImageThresholdBinaryInverse {
    extern_methods!(
        /// initialize a MPSImageThresholdBinaryInverse filter
        ///
        /// Parameter `device`: The device the filter will run on
        ///
        /// Parameter `thresholdValue`: The threshold value to use
        ///
        /// Parameter `maximumValue`: The maximum value to use
        ///
        /// Parameter `transform`: This matrix is an array of 3 floats.
        /// The default if no transform is specifed is BT.601/JPEG: {0.299f, 0.587f, 0.114f};
        ///
        /// # Safety
        ///
        /// `transform` must be a valid pointer or null.
        #[unsafe(method(initWithDevice:thresholdValue:maximumValue:linearGrayColorTransform:))]
        #[unsafe(method_family = init)]
        pub unsafe fn initWithDevice_thresholdValue_maximumValue_linearGrayColorTransform(
            this: Allocated<Self>,
            device: &ProtocolObject<dyn MTLDevice>,
            threshold_value: c_float,
            maximum_value: c_float,
            transform: *const c_float,
        ) -> Retained<Self>;

        /// NSSecureCoding compatability
        ///
        /// While the standard NSSecureCoding/NSCoding method
        /// -initWithCoder: should work, since the file can't
        /// know which device your data is allocated on, we
        /// have to guess and may guess incorrectly.  To avoid
        /// that problem, use initWithCoder:device instead.
        ///
        /// Parameter `aDecoder`: The NSCoder subclass with your serialized MPSKernel
        ///
        /// Parameter `device`: The MTLDevice on which to make the MPSKernel
        ///
        /// Returns: A new MPSKernel object, or nil if failure.
        ///
        /// # Safety
        ///
        /// `a_decoder` possibly has further requirements.
        #[unsafe(method(initWithCoder:device:))]
        #[unsafe(method_family = init)]
        pub unsafe fn initWithCoder_device(
            this: Allocated<Self>,
            a_decoder: &NSCoder,
            device: &ProtocolObject<dyn MTLDevice>,
        ) -> Option<Retained<Self>>;

        #[unsafe(method(initWithDevice:))]
        #[unsafe(method_family = init)]
        pub unsafe fn initWithDevice(
            this: Allocated<Self>,
            device: &ProtocolObject<dyn MTLDevice>,
        ) -> Retained<Self>;

        /// The threshold value used to init the threshold filter
        #[unsafe(method(thresholdValue))]
        #[unsafe(method_family = none)]
        pub unsafe fn thresholdValue(&self) -> c_float;

        /// The maximum value used to init the threshold filter
        #[unsafe(method(maximumValue))]
        #[unsafe(method_family = none)]
        pub unsafe fn maximumValue(&self) -> c_float;

        /// The color transform used to init the threshold filter
        #[unsafe(method(transform))]
        #[unsafe(method_family = none)]
        pub unsafe fn transform(&self) -> NonNull<c_float>;
    );
}

/// Methods declared on superclass `MPSKernel`.
#[cfg(all(feature = "MPSCore", feature = "MPSImageKernel", feature = "MPSKernel"))]
impl MPSImageThresholdBinaryInverse {
    extern_methods!(
        /// Called by NSCoder to decode MPSKernels
        ///
        /// This isn't the right interface to decode a MPSKernel, but
        /// it is the one that NSCoder uses. To enable your NSCoder
        /// (e.g. NSKeyedUnarchiver) to set which device to use
        /// extend the object to adopt the MPSDeviceProvider
        /// protocol. Otherwise, the Metal system default device
        /// will be used.
        ///
        /// # Safety
        ///
        /// `a_decoder` possibly has further requirements.
        #[unsafe(method(initWithCoder:))]
        #[unsafe(method_family = init)]
        pub unsafe fn initWithCoder(
            this: Allocated<Self>,
            a_decoder: &NSCoder,
        ) -> Option<Retained<Self>>;
    );
}

/// Methods declared on superclass `NSObject`.
#[cfg(all(feature = "MPSCore", feature = "MPSImageKernel", feature = "MPSKernel"))]
impl MPSImageThresholdBinaryInverse {
    extern_methods!(
        #[unsafe(method(init))]
        #[unsafe(method_family = init)]
        pub unsafe fn init(this: Allocated<Self>) -> Retained<Self>;

        #[unsafe(method(new))]
        #[unsafe(method_family = new)]
        pub unsafe fn new() -> Retained<Self>;
    );
}

extern_class!(
    /// A filter that clamps the return value to an upper specified value.
    ///
    /// ## Overview
    ///
    /// An [`MPSImageThresholdTruncate`](https://developer.apple.com/documentation/metalperformanceshaders/mpsimagethresholdtruncate) filter converts a single channel image to a binary image. If the input image is not a single channel image, the function first converts the input image into a single channel luminance image using the linear gray color transform, and then it applies the threshold.
    ///
    /// The following listing shows the threshold truncate function.
    ///
    /// Listing 1. Threshold truncate function
    ///
    /// ```other
    /// destinationPixelValue = sourcePixelValue > thresholdValue ? thresholdValue : sourcePixelValue
    /// ```
    ///
    ///
    /// The MPSImageThresholdTruncate filter applies a fixed-level threshold to each pixel in the image:
    /// The threshold functions convert a single channel image to a binary image.
    /// If the input image is not a single channel image, convert the inputimage to a single channel
    /// luminance image using the linearGrayColorTransform and then apply the threshold.
    /// The ThresholdTruncate function is:
    /// destinationPixelValue = sourcePixelValue > thresholdValue ? thresholdValue : sourcePixelValue
    #[unsafe(super(MPSUnaryImageKernel, MPSKernel, NSObject))]
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(all(feature = "MPSCore", feature = "MPSImageKernel", feature = "MPSKernel"))]
    pub struct MPSImageThresholdTruncate;
);

#[cfg(all(feature = "MPSCore", feature = "MPSImageKernel", feature = "MPSKernel"))]
extern_conformance!(
    unsafe impl NSCoding for MPSImageThresholdTruncate {}
);

#[cfg(all(feature = "MPSCore", feature = "MPSImageKernel", feature = "MPSKernel"))]
extern_conformance!(
    unsafe impl NSCopying for MPSImageThresholdTruncate {}
);

#[cfg(all(feature = "MPSCore", feature = "MPSImageKernel", feature = "MPSKernel"))]
unsafe impl CopyingHelper for MPSImageThresholdTruncate {
    type Result = Self;
}

#[cfg(all(feature = "MPSCore", feature = "MPSImageKernel", feature = "MPSKernel"))]
extern_conformance!(
    unsafe impl NSObjectProtocol for MPSImageThresholdTruncate {}
);

#[cfg(all(feature = "MPSCore", feature = "MPSImageKernel", feature = "MPSKernel"))]
extern_conformance!(
    unsafe impl NSSecureCoding for MPSImageThresholdTruncate {}
);

#[cfg(all(feature = "MPSCore", feature = "MPSImageKernel", feature = "MPSKernel"))]
impl MPSImageThresholdTruncate {
    extern_methods!(
        /// initialize a MPSImageThresholdTruncate filter
        ///
        /// Parameter `device`: The device the filter will run on
        ///
        /// Parameter `thresholdValue`: The threshold value to use
        ///
        /// Parameter `transform`: This matrix is an array of 3 floats.
        /// The default if no transform is specifed is BT.601/JPEG: {0.299f, 0.587f, 0.114f};
        ///
        /// # Safety
        ///
        /// `transform` must be a valid pointer or null.
        #[unsafe(method(initWithDevice:thresholdValue:linearGrayColorTransform:))]
        #[unsafe(method_family = init)]
        pub unsafe fn initWithDevice_thresholdValue_linearGrayColorTransform(
            this: Allocated<Self>,
            device: &ProtocolObject<dyn MTLDevice>,
            threshold_value: c_float,
            transform: *const c_float,
        ) -> Retained<Self>;

        /// NSSecureCoding compatability
        ///
        /// While the standard NSSecureCoding/NSCoding method
        /// -initWithCoder: should work, since the file can't
        /// know which device your data is allocated on, we
        /// have to guess and may guess incorrectly.  To avoid
        /// that problem, use initWithCoder:device instead.
        ///
        /// Parameter `aDecoder`: The NSCoder subclass with your serialized MPSKernel
        ///
        /// Parameter `device`: The MTLDevice on which to make the MPSKernel
        ///
        /// Returns: A new MPSKernel object, or nil if failure.
        ///
        /// # Safety
        ///
        /// `a_decoder` possibly has further requirements.
        #[unsafe(method(initWithCoder:device:))]
        #[unsafe(method_family = init)]
        pub unsafe fn initWithCoder_device(
            this: Allocated<Self>,
            a_decoder: &NSCoder,
            device: &ProtocolObject<dyn MTLDevice>,
        ) -> Option<Retained<Self>>;

        #[unsafe(method(initWithDevice:))]
        #[unsafe(method_family = init)]
        pub unsafe fn initWithDevice(
            this: Allocated<Self>,
            device: &ProtocolObject<dyn MTLDevice>,
        ) -> Retained<Self>;

        /// The threshold value used to init the threshold filter
        #[unsafe(method(thresholdValue))]
        #[unsafe(method_family = none)]
        pub unsafe fn thresholdValue(&self) -> c_float;

        /// The color transform used to init the threshold filter
        #[unsafe(method(transform))]
        #[unsafe(method_family = none)]
        pub unsafe fn transform(&self) -> NonNull<c_float>;
    );
}

/// Methods declared on superclass `MPSKernel`.
#[cfg(all(feature = "MPSCore", feature = "MPSImageKernel", feature = "MPSKernel"))]
impl MPSImageThresholdTruncate {
    extern_methods!(
        /// Called by NSCoder to decode MPSKernels
        ///
        /// This isn't the right interface to decode a MPSKernel, but
        /// it is the one that NSCoder uses. To enable your NSCoder
        /// (e.g. NSKeyedUnarchiver) to set which device to use
        /// extend the object to adopt the MPSDeviceProvider
        /// protocol. Otherwise, the Metal system default device
        /// will be used.
        ///
        /// # Safety
        ///
        /// `a_decoder` possibly has further requirements.
        #[unsafe(method(initWithCoder:))]
        #[unsafe(method_family = init)]
        pub unsafe fn initWithCoder(
            this: Allocated<Self>,
            a_decoder: &NSCoder,
        ) -> Option<Retained<Self>>;
    );
}

/// Methods declared on superclass `NSObject`.
#[cfg(all(feature = "MPSCore", feature = "MPSImageKernel", feature = "MPSKernel"))]
impl MPSImageThresholdTruncate {
    extern_methods!(
        #[unsafe(method(init))]
        #[unsafe(method_family = init)]
        pub unsafe fn init(this: Allocated<Self>) -> Retained<Self>;

        #[unsafe(method(new))]
        #[unsafe(method_family = new)]
        pub unsafe fn new() -> Retained<Self>;
    );
}

extern_class!(
    /// A filter that returns the original value for each pixel with a value greater than a specified threshold or 0 otherwise.
    ///
    /// ## Overview
    ///
    /// An [`MPSImageThresholdToZero`](https://developer.apple.com/documentation/metalperformanceshaders/mpsimagethresholdtozero) filter converts a single channel image to a binary image. If the input image is not a single channel image, the function first converts the input image into a single channel luminance image using the linear gray color transform, and then it applies the threshold.
    ///
    /// The following listing shows the threshold to zero function.
    ///
    /// Listing 1. Threshold to zero function
    ///
    /// ```other
    /// destinationPixelValue = sourcePixelValue > thresholdValue ? sourcePixelValue : 0
    /// ```
    ///
    ///
    /// The MPSImageThresholdToZero filter applies a fixed-level threshold to each pixel in the image.
    /// The threshold functions convert a single channel image to a binary image.
    /// If the input image is not a single channel image, convert the inputimage to a single channel
    /// luminance image using the linearGrayColorTransform and then apply the threshold.
    /// The ThresholdToZero function is:
    /// destinationPixelValue = sourcePixelValue > thresholdValue ? sourcePixelValue : 0
    #[unsafe(super(MPSUnaryImageKernel, MPSKernel, NSObject))]
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(all(feature = "MPSCore", feature = "MPSImageKernel", feature = "MPSKernel"))]
    pub struct MPSImageThresholdToZero;
);

#[cfg(all(feature = "MPSCore", feature = "MPSImageKernel", feature = "MPSKernel"))]
extern_conformance!(
    unsafe impl NSCoding for MPSImageThresholdToZero {}
);

#[cfg(all(feature = "MPSCore", feature = "MPSImageKernel", feature = "MPSKernel"))]
extern_conformance!(
    unsafe impl NSCopying for MPSImageThresholdToZero {}
);

#[cfg(all(feature = "MPSCore", feature = "MPSImageKernel", feature = "MPSKernel"))]
unsafe impl CopyingHelper for MPSImageThresholdToZero {
    type Result = Self;
}

#[cfg(all(feature = "MPSCore", feature = "MPSImageKernel", feature = "MPSKernel"))]
extern_conformance!(
    unsafe impl NSObjectProtocol for MPSImageThresholdToZero {}
);

#[cfg(all(feature = "MPSCore", feature = "MPSImageKernel", feature = "MPSKernel"))]
extern_conformance!(
    unsafe impl NSSecureCoding for MPSImageThresholdToZero {}
);

#[cfg(all(feature = "MPSCore", feature = "MPSImageKernel", feature = "MPSKernel"))]
impl MPSImageThresholdToZero {
    extern_methods!(
        /// initialize a MPSImageThresholdToZero filter
        ///
        /// Parameter `device`: The device the filter will run on
        ///
        /// Parameter `thresholdValue`: The threshold value to use
        ///
        /// Parameter `transform`: This matrix is an array of 3 floats.
        /// The default if no transform is specifed is BT.601/JPEG: {0.299f, 0.587f, 0.114f};
        ///
        /// # Safety
        ///
        /// `transform` must be a valid pointer or null.
        #[unsafe(method(initWithDevice:thresholdValue:linearGrayColorTransform:))]
        #[unsafe(method_family = init)]
        pub unsafe fn initWithDevice_thresholdValue_linearGrayColorTransform(
            this: Allocated<Self>,
            device: &ProtocolObject<dyn MTLDevice>,
            threshold_value: c_float,
            transform: *const c_float,
        ) -> Retained<Self>;

        #[unsafe(method(initWithDevice:))]
        #[unsafe(method_family = init)]
        pub unsafe fn initWithDevice(
            this: Allocated<Self>,
            device: &ProtocolObject<dyn MTLDevice>,
        ) -> Retained<Self>;

        /// NSSecureCoding compatability
        ///
        /// While the standard NSSecureCoding/NSCoding method
        /// -initWithCoder: should work, since the file can't
        /// know which device your data is allocated on, we
        /// have to guess and may guess incorrectly.  To avoid
        /// that problem, use initWithCoder:device instead.
        ///
        /// Parameter `aDecoder`: The NSCoder subclass with your serialized MPSKernel
        ///
        /// Parameter `device`: The MTLDevice on which to make the MPSKernel
        ///
        /// Returns: A new MPSKernel object, or nil if failure.
        ///
        /// # Safety
        ///
        /// `a_decoder` possibly has further requirements.
        #[unsafe(method(initWithCoder:device:))]
        #[unsafe(method_family = init)]
        pub unsafe fn initWithCoder_device(
            this: Allocated<Self>,
            a_decoder: &NSCoder,
            device: &ProtocolObject<dyn MTLDevice>,
        ) -> Option<Retained<Self>>;

        /// The threshold value used to init the threshold filter
        #[unsafe(method(thresholdValue))]
        #[unsafe(method_family = none)]
        pub unsafe fn thresholdValue(&self) -> c_float;

        /// The color transform used to init the threshold filter
        #[unsafe(method(transform))]
        #[unsafe(method_family = none)]
        pub unsafe fn transform(&self) -> NonNull<c_float>;
    );
}

/// Methods declared on superclass `MPSKernel`.
#[cfg(all(feature = "MPSCore", feature = "MPSImageKernel", feature = "MPSKernel"))]
impl MPSImageThresholdToZero {
    extern_methods!(
        /// Called by NSCoder to decode MPSKernels
        ///
        /// This isn't the right interface to decode a MPSKernel, but
        /// it is the one that NSCoder uses. To enable your NSCoder
        /// (e.g. NSKeyedUnarchiver) to set which device to use
        /// extend the object to adopt the MPSDeviceProvider
        /// protocol. Otherwise, the Metal system default device
        /// will be used.
        ///
        /// # Safety
        ///
        /// `a_decoder` possibly has further requirements.
        #[unsafe(method(initWithCoder:))]
        #[unsafe(method_family = init)]
        pub unsafe fn initWithCoder(
            this: Allocated<Self>,
            a_decoder: &NSCoder,
        ) -> Option<Retained<Self>>;
    );
}

/// Methods declared on superclass `NSObject`.
#[cfg(all(feature = "MPSCore", feature = "MPSImageKernel", feature = "MPSKernel"))]
impl MPSImageThresholdToZero {
    extern_methods!(
        #[unsafe(method(init))]
        #[unsafe(method_family = init)]
        pub unsafe fn init(this: Allocated<Self>) -> Retained<Self>;

        #[unsafe(method(new))]
        #[unsafe(method_family = new)]
        pub unsafe fn new() -> Retained<Self>;
    );
}

extern_class!(
    /// A filter that returns 0 for each pixel with a value greater than a specified threshold or the original value otherwise.
    ///
    /// ## Overview
    ///
    /// An [`MPSImageThresholdToZeroInverse`](https://developer.apple.com/documentation/metalperformanceshaders/mpsimagethresholdtozeroinverse) filter converts a single channel image to a binary image. If the input image is not a single channel image, the function first converts the input image into a single channel luminance image using the linear gray color transform, and then it applies the threshold.
    ///
    /// The following listing shows the threshold to zero inverse function.
    ///
    /// Listing 1. Threshold to zero inverse function
    ///
    /// ```other
    /// destinationPixelValue = sourcePixelValue > thresholdValue ? 0 : sourcePixelValue
    /// ```
    ///
    ///
    /// The MPSImageThresholdToZeroInverse filter applies a fixed-level threshold to each pixel in the image.
    /// The threshold functions convert a single channel image to a binary image.
    /// If the input image is not a single channel image, convert the inputimage to a single channel
    /// luminance image using the linearGrayColorTransform and then apply the threshold.
    /// The ThresholdToZeroINverse function is:
    /// destinationPixelValue = sourcePixelValue > thresholdValue ? 0 : sourcePixelValue
    #[unsafe(super(MPSUnaryImageKernel, MPSKernel, NSObject))]
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(all(feature = "MPSCore", feature = "MPSImageKernel", feature = "MPSKernel"))]
    pub struct MPSImageThresholdToZeroInverse;
);

#[cfg(all(feature = "MPSCore", feature = "MPSImageKernel", feature = "MPSKernel"))]
extern_conformance!(
    unsafe impl NSCoding for MPSImageThresholdToZeroInverse {}
);

#[cfg(all(feature = "MPSCore", feature = "MPSImageKernel", feature = "MPSKernel"))]
extern_conformance!(
    unsafe impl NSCopying for MPSImageThresholdToZeroInverse {}
);

#[cfg(all(feature = "MPSCore", feature = "MPSImageKernel", feature = "MPSKernel"))]
unsafe impl CopyingHelper for MPSImageThresholdToZeroInverse {
    type Result = Self;
}

#[cfg(all(feature = "MPSCore", feature = "MPSImageKernel", feature = "MPSKernel"))]
extern_conformance!(
    unsafe impl NSObjectProtocol for MPSImageThresholdToZeroInverse {}
);

#[cfg(all(feature = "MPSCore", feature = "MPSImageKernel", feature = "MPSKernel"))]
extern_conformance!(
    unsafe impl NSSecureCoding for MPSImageThresholdToZeroInverse {}
);

#[cfg(all(feature = "MPSCore", feature = "MPSImageKernel", feature = "MPSKernel"))]
impl MPSImageThresholdToZeroInverse {
    extern_methods!(
        /// initialize a MPSImageThresholdToZeroInverse filter
        ///
        /// Parameter `device`: The device the filter will run on
        ///
        /// Parameter `thresholdValue`: The threshold value to use
        ///
        /// Parameter `transform`: This matrix is an array of 3 floats.
        /// The default if no transform is specifed is BT.601/JPEG: {0.299f, 0.587f, 0.114f};
        ///
        /// # Safety
        ///
        /// `transform` must be a valid pointer or null.
        #[unsafe(method(initWithDevice:thresholdValue:linearGrayColorTransform:))]
        #[unsafe(method_family = init)]
        pub unsafe fn initWithDevice_thresholdValue_linearGrayColorTransform(
            this: Allocated<Self>,
            device: &ProtocolObject<dyn MTLDevice>,
            threshold_value: c_float,
            transform: *const c_float,
        ) -> Retained<Self>;

        /// NSSecureCoding compatability
        ///
        /// While the standard NSSecureCoding/NSCoding method
        /// -initWithCoder: should work, since the file can't
        /// know which device your data is allocated on, we
        /// have to guess and may guess incorrectly.  To avoid
        /// that problem, use initWithCoder:device instead.
        ///
        /// Parameter `aDecoder`: The NSCoder subclass with your serialized MPSKernel
        ///
        /// Parameter `device`: The MTLDevice on which to make the MPSKernel
        ///
        /// Returns: A new MPSKernel object, or nil if failure.
        ///
        /// # Safety
        ///
        /// `a_decoder` possibly has further requirements.
        #[unsafe(method(initWithCoder:device:))]
        #[unsafe(method_family = init)]
        pub unsafe fn initWithCoder_device(
            this: Allocated<Self>,
            a_decoder: &NSCoder,
            device: &ProtocolObject<dyn MTLDevice>,
        ) -> Option<Retained<Self>>;

        #[unsafe(method(initWithDevice:))]
        #[unsafe(method_family = init)]
        pub unsafe fn initWithDevice(
            this: Allocated<Self>,
            device: &ProtocolObject<dyn MTLDevice>,
        ) -> Retained<Self>;

        /// The threshold value used to init the threshold filter
        #[unsafe(method(thresholdValue))]
        #[unsafe(method_family = none)]
        pub unsafe fn thresholdValue(&self) -> c_float;

        /// The color transform used to init the threshold filter
        #[unsafe(method(transform))]
        #[unsafe(method_family = none)]
        pub unsafe fn transform(&self) -> NonNull<c_float>;
    );
}

/// Methods declared on superclass `MPSKernel`.
#[cfg(all(feature = "MPSCore", feature = "MPSImageKernel", feature = "MPSKernel"))]
impl MPSImageThresholdToZeroInverse {
    extern_methods!(
        /// Called by NSCoder to decode MPSKernels
        ///
        /// This isn't the right interface to decode a MPSKernel, but
        /// it is the one that NSCoder uses. To enable your NSCoder
        /// (e.g. NSKeyedUnarchiver) to set which device to use
        /// extend the object to adopt the MPSDeviceProvider
        /// protocol. Otherwise, the Metal system default device
        /// will be used.
        ///
        /// # Safety
        ///
        /// `a_decoder` possibly has further requirements.
        #[unsafe(method(initWithCoder:))]
        #[unsafe(method_family = init)]
        pub unsafe fn initWithCoder(
            this: Allocated<Self>,
            a_decoder: &NSCoder,
        ) -> Option<Retained<Self>>;
    );
}

/// Methods declared on superclass `NSObject`.
#[cfg(all(feature = "MPSCore", feature = "MPSImageKernel", feature = "MPSKernel"))]
impl MPSImageThresholdToZeroInverse {
    extern_methods!(
        #[unsafe(method(init))]
        #[unsafe(method_family = init)]
        pub unsafe fn init(this: Allocated<Self>) -> Retained<Self>;

        #[unsafe(method(new))]
        #[unsafe(method_family = new)]
        pub unsafe fn new() -> Retained<Self>;
    );
}
