//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use core::ffi::*;
use core::ptr::NonNull;
#[cfg(feature = "dispatch2")]
use dispatch2::*;
use objc2::__framework_prelude::*;
#[cfg(feature = "objc2-core-media")]
use objc2_core_media::*;
#[cfg(feature = "objc2-core-video")]
use objc2_core_video::*;
use objc2_foundation::*;

use crate::*;

extern "C" {
    /// [Apple's documentation](https://developer.apple.com/documentation/avfoundation/avsamplebuffervideorendererdidfailtodecodenotification?language=objc)
    pub static AVSampleBufferVideoRendererDidFailToDecodeNotification: &'static NSNotificationName;
}

extern "C" {
    /// [Apple's documentation](https://developer.apple.com/documentation/avfoundation/avsamplebuffervideorendererdidfailtodecodenotificationerrorkey?language=objc)
    pub static AVSampleBufferVideoRendererDidFailToDecodeNotificationErrorKey: &'static NSString;
}

extern "C" {
    /// [Apple's documentation](https://developer.apple.com/documentation/avfoundation/avsamplebuffervideorendererrequiresflushtoresumedecodingdidchangenotification?language=objc)
    pub static AVSampleBufferVideoRendererRequiresFlushToResumeDecodingDidChangeNotification:
        &'static NSNotificationName;
}

extern "C" {
    /// [Apple's documentation](https://developer.apple.com/documentation/avfoundation/avsamplebuffervideorendererrequiresflushtoresumedecodingdidchangenotificationrequiresflushkey?language=objc)
    pub static AVSampleBufferVideoRendererRequiresFlushToResumeDecodingDidChangeNotificationRequiresFlushKey:
        &'static NSString;
}

extern_class!(
    /// AVSampleBufferVideoRenderer provides a mechanism to enqueue sample buffers for rendering.
    ///
    /// See also [Apple's documentation](https://developer.apple.com/documentation/avfoundation/avsamplebuffervideorenderer?language=objc)
    #[unsafe(super(NSObject))]
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub struct AVSampleBufferVideoRenderer;
);

#[cfg(feature = "AVQueuedSampleBufferRendering")]
extern_conformance!(
    unsafe impl AVQueuedSampleBufferRendering for AVSampleBufferVideoRenderer {}
);

extern_conformance!(
    unsafe impl NSObjectProtocol for AVSampleBufferVideoRenderer {}
);

impl AVSampleBufferVideoRenderer {
    extern_methods!(
        #[cfg(feature = "AVQueuedSampleBufferRendering")]
        /// The ability of the video renderer to be used for enqueueing sample buffers.
        ///
        /// The value of this property is an AVQueuedSampleBufferRenderingStatus that indicates whether the receiver can be used for enqueueing and rendering sample buffers. When the value of this property is AVQueuedSampleBufferRenderingStatusFailed, clients can check the value of the error property to determine the failure. To resume rendering sample buffers using the video renderer after a failure, clients must first reset the status to AVQueuedSampleBufferRenderingStatusUnknown. This can be achieved by invoking -flush on the video renderer.
        /// This property is key value observable.
        #[unsafe(method(status))]
        #[unsafe(method_family = none)]
        pub unsafe fn status(&self) -> AVQueuedSampleBufferRenderingStatus;

        /// If the video renderer's status is AVQueuedSampleBufferRenderingStatusFailed, this describes the error that caused the failure.
        ///
        /// The value of this property is an NSError that describes what caused the video renderer to no longer be able to enqueue sample buffers. If the status is not AVQueuedSampleBufferRenderingStatusFailed, the value of this property is nil.
        #[unsafe(method(error))]
        #[unsafe(method_family = none)]
        pub unsafe fn error(&self) -> Option<Retained<NSError>>;

        /// Indicates that the receiver is in a state where it requires a call to -flush to continue decoding frames.
        ///
        /// When the application enters a state where use of video decoder resources is not permissible, the value of this property changes to YES along with the video renderer's status changing to AVQueuedSampleBufferRenderingStatusFailed.
        /// To resume rendering sample buffers using the video renderer after this property's value is YES, clients must first reset the video renderer by calling flush or flushWithRemovalOfDisplayedImage:completionHandler:.
        /// Clients can track changes to this property via AVSampleBufferVideoRendererRequiresFlushToResumeDecodingDidChangeNotification.
        /// This property is not key value observable.
        #[unsafe(method(requiresFlushToResumeDecoding))]
        #[unsafe(method_family = none)]
        pub unsafe fn requiresFlushToResumeDecoding(&self) -> bool;

        #[cfg(feature = "block2")]
        /// Instructs the video renderer to discard pending enqueued sample buffers and call the provided block when complete.
        ///
        /// A flush resets decoder state. The next frame passed to enqueueSampleBuffer: should be an IDR frame (also known as a key frame or sync sample).
        ///
        /// - Parameter removeDisplayedImage: Set YES to remove any currently displayed image, NO to preserve any current image.
        /// - Parameter handler: The handler to invoke when flush operation is complete. May be nil.
        #[unsafe(method(flushWithRemovalOfDisplayedImage:completionHandler:))]
        #[unsafe(method_family = none)]
        pub unsafe fn flushWithRemovalOfDisplayedImage_completionHandler(
            &self,
            remove_displayed_image: bool,
            handler: Option<&block2::SendableBlock<'static, fn()>>,
        );

        #[cfg(feature = "objc2-core-media")]
        /// Sends a sample buffer in order to render its contents.
        ///
        /// Video-specific notes:
        ///
        /// If sampleBuffer has the kCMSampleAttachmentKey_DoNotDisplay attachment set to kCFBooleanTrue, the frame will be decoded but not displayed. Otherwise, if sampleBuffer has the kCMSampleAttachmentKey_DisplayImmediately attachment set to kCFBooleanTrue, the decoded image will be displayed as soon as possible, replacing all previously enqueued images regardless of their timestamps. Otherwise, the decoded image will be displayed at sampleBuffer's output presentation timestamp, as interpreted by the timebase.
        ///
        /// To schedule the removal of previous images at a specific timestamp, enqueue a marker sample buffer containing no samples, with the kCMSampleBufferAttachmentKey_EmptyMedia attachment set to kCFBooleanTrue.
        ///
        /// IMPORTANT NOTE: attachments with the kCMSampleAttachmentKey_ prefix must be set via CMSampleBufferGetSampleAttachmentsArray and CFDictionarySetValue. Attachments with the kCMSampleBufferAttachmentKey_ prefix must be set via CMSetAttachment.
        ///
        /// The combination of either a non-NULL controlTimebase or an AVSampleBufferRenderSynchronizer with the use of kCMSampleAttachmentKey_DisplayImmediately as an attachment to the CMSampleBuffers that are enqueued for display is not recommended.
        #[unsafe(method(enqueueSampleBuffer:))]
        #[unsafe(method_family = none)]
        pub unsafe fn enqueueSampleBuffer(&self, sample_buffer: &CMSampleBuffer);

        /// Instructs the receiver to discard pending enqueued sample buffers.
        ///
        /// Additional sample buffers can be appended after -flush.
        ///
        /// Video-specific notes:
        ///
        /// It is not possible to determine which sample buffers have been decoded, so the next frame passed to enqueueSampleBuffer: should be an IDR frame (also known as a key frame or sync sample).
        #[unsafe(method(flush))]
        #[unsafe(method_family = none)]
        pub unsafe fn flush(&self);

        /// Indicates the readiness of the receiver to accept more sample buffers.
        ///
        /// An object conforming to AVQueuedSampleBufferRendering keeps track of the occupancy levels of its internal queues for the benefit of clients that enqueue sample buffers from non-real-time sources -- i.e., clients that can supply sample buffers faster than they are consumed, and so need to decide when to hold back.
        ///
        /// Clients enqueueing sample buffers from non-real-time sources may hold off from generating or obtaining more sample buffers to enqueue when the value of readyForMoreMediaData is NO.
        ///
        /// It is safe to call enqueueSampleBuffer: when readyForMoreMediaData is NO, but it is a bad idea to enqueue sample buffers without bound.
        ///
        /// To help with control of the non-real-time supply of sample buffers, such clients can use -requestMediaDataWhenReadyOnQueue:usingBlock in order to specify a block that the receiver should invoke whenever it's ready for sample buffers to be appended.
        ///
        /// The value of readyForMoreMediaData will often change from NO to YES asynchronously, as previously supplied sample buffers are decoded and rendered.
        ///
        /// This property is not key value observable.
        #[unsafe(method(isReadyForMoreMediaData))]
        #[unsafe(method_family = none)]
        pub unsafe fn isReadyForMoreMediaData(&self) -> bool;

        #[cfg(all(feature = "block2", feature = "dispatch2"))]
        /// Instructs the target to invoke a client-supplied block repeatedly, at its convenience, in order to gather sample buffers for playback.
        ///
        /// The block should enqueue sample buffers to the receiver either until the receiver's readyForMoreMediaData property becomes NO or until there is no more data to supply. When the receiver has decoded enough of the media data it has received that it becomes ready for more media data again, it will invoke the block again in order to obtain more.
        ///
        /// If this method is called multiple times, only the last call is effective. Call stopRequestingMediaData to cancel this request.
        ///
        /// Each call to requestMediaDataWhenReadyOnQueue:usingBlock: should be paired with a corresponding call to stopRequestingMediaData:. Releasing the AVQueuedSampleBufferRendering object without a call to stopRequestingMediaData will result in undefined behavior.
        ///
        /// # Safety
        ///
        /// `queue` possibly has additional threading requirements.
        #[unsafe(method(requestMediaDataWhenReadyOnQueue:usingBlock:))]
        #[unsafe(method_family = none)]
        pub unsafe fn requestMediaDataWhenReadyOnQueue_usingBlock(
            &self,
            queue: &DispatchQueue,
            block: &block2::SendableBlock<'static, fn()>,
        );

        /// Cancels any current requestMediaDataWhenReadyOnQueue:usingBlock: call.
        ///
        /// This method may be called from outside the block or from within the block.
        #[unsafe(method(stopRequestingMediaData))]
        #[unsafe(method_family = none)]
        pub unsafe fn stopRequestingMediaData(&self);

        /// Indicates whether the enqueued media data meets the renderer's preroll level.
        ///
        /// Clients should fetch the value of this property to learn if the renderer has had enough media data enqueued to start playback reliably. Starting playback when this property is NO may prevent smooth playback following an immediate start.
        #[unsafe(method(hasSufficientMediaDataForReliablePlaybackStart))]
        #[unsafe(method_family = none)]
        pub unsafe fn hasSufficientMediaDataForReliablePlaybackStart(&self) -> bool;
    );
}

/// Methods declared on superclass `NSObject`.
impl AVSampleBufferVideoRenderer {
    extern_methods!(
        #[unsafe(method(init))]
        #[unsafe(method_family = init)]
        pub unsafe fn init(this: Allocated<Self>) -> Retained<Self>;

        #[unsafe(method(new))]
        #[unsafe(method_family = new)]
        pub unsafe fn new() -> Retained<Self>;
    );
}

/// AVSampleBufferVideoRendererPixelBufferOutput.
impl AVSampleBufferVideoRenderer {
    extern_methods!(
        #[cfg(feature = "objc2-core-video")]
        /// Returns a retained reference to the pixel buffer currently displayed in the AVSampleBufferVideoRenderer's target. This will return NULL if the displayed pixel buffer is protected, no image is currently being displayed, or if the image is unavailable.
        ///
        /// This will return NULL if the rate is non-zero. Clients must release the pixel buffer after use.
        ///
        /// Do not write to the returned CVPixelBuffer's attachments or pixel data.
        #[unsafe(method(copyDisplayedPixelBuffer))]
        #[unsafe(method_family = copy)]
        pub unsafe fn copyDisplayedPixelBuffer(&self) -> Option<Retained<CVPixelBuffer>>;
    );
}

/// AVSampleBufferVideoRendererPowerOptimization.
impl AVSampleBufferVideoRenderer {
    extern_methods!(
        #[cfg(feature = "objc2-core-media")]
        /// Promises, for the purpose of enabling power optimizations, that future sample buffers will have PTS values no less than a specified lower-bound PTS.
        ///
        /// Only applicable for forward playback.
        /// Sending this message and later calling -enqueueSampleBuffer: with a buffer with a lower PTS has the potential to lead to dropping that later buffer.
        /// For best results, call -expectMinimumUpcomingSampleBufferPresentationTime: regularly, in between calls to -enqueueSampleBuffer:, to advance the lower-bound PTS.
        /// Messaging -flush resets such expectations.
        /// (For example, it's OK to make this expectation, then in response to a seek back, flush and then enqueue buffers with lower PTS values.)
        ///
        /// - Parameter minimumUpcomingPresentationTime: A lower bound on PTS values for buffers that will be passed to -enqueueSampleBuffer: in the future.
        #[unsafe(method(expectMinimumUpcomingSampleBufferPresentationTime:))]
        #[unsafe(method_family = none)]
        pub unsafe fn expectMinimumUpcomingSampleBufferPresentationTime(
            &self,
            minimum_upcoming_presentation_time: CMTime,
        );

        /// Promises, for the purpose of enabling power optimizations, that future sample buffers will have monotonically increasing PTS values.
        ///
        /// Only applicable for forward playback.
        /// Sending this message and later calling -enqueueSampleBuffer: with a buffer with a lower PTS than any previously enqueued PTS has the potential to lead to dropped buffers.
        /// Messaging -flush resets such expectations.
        #[unsafe(method(expectMonotonicallyIncreasingUpcomingSampleBufferPresentationTimes))]
        #[unsafe(method_family = none)]
        pub unsafe fn expectMonotonicallyIncreasingUpcomingSampleBufferPresentationTimes(&self);

        /// Resets previously-promised expectations about upcoming sample buffer PTSs.
        ///
        /// This undoes the state set by messaging -expectMinimumUpcomingSampleBufferPresentationTime: or -expectMonotonicallyIncreasingUpcomingSampleBufferPresentationTimes.
        /// If you didn't use either of those, you don't have to use this.
        #[unsafe(method(resetUpcomingSampleBufferPresentationTimeExpectations))]
        #[unsafe(method_family = none)]
        pub unsafe fn resetUpcomingSampleBufferPresentationTimeExpectations(&self);

        /// Recommended pixel buffer attributes for optimal performance when using CMSampleBuffers containing CVPixelBuffers.
        ///
        /// The returned dictionary does not contain all of the attributes needed for creating pixel buffers.
        /// Use ``CVPixelBufferCreateResolvedAttributesDictionary()`` to reconcile these attributes with the pixel buffer creation attributes.
        #[unsafe(method(recommendedPixelBufferAttributes))]
        #[unsafe(method_family = none)]
        pub unsafe fn recommendedPixelBufferAttributes(
            &self,
        ) -> Retained<NSDictionary<NSString, AnyObject>>;
    );
}

/// AVSampleBufferVideoRendererVideoPerformanceMetrics.
impl AVSampleBufferVideoRenderer {
    extern_methods!(
        #[cfg(all(feature = "AVVideoPerformanceMetrics", feature = "block2"))]
        /// Gathers a snapshot of the video performance metrics and calls the completion handler with the results.
        ///
        /// If there are no performance metrics available, the completion handler will be called with nil videoPerformanceMetrics.
        ///
        /// - Parameter completionHandler: The handler to invoke with the video performance metrics.
        #[unsafe(method(loadVideoPerformanceMetricsWithCompletionHandler:))]
        #[unsafe(method_family = none)]
        pub unsafe fn loadVideoPerformanceMetricsWithCompletionHandler(
            &self,
            completion_handler: &block2::SendableBlock<'static, fn(*mut AVVideoPerformanceMetrics)>,
        );
    );
}
