//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use core::ffi::*;
use core::ptr::NonNull;
use objc2::__framework_prelude::*;
use objc2_foundation::*;

use crate::*;

extern_class!(
    /// [Apple's documentation](https://developer.apple.com/documentation/safariservices/sfsafariextension?language=objc)
    #[unsafe(super(NSObject))]
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub struct SFSafariExtension;
);

extern_conformance!(
    unsafe impl NSObjectProtocol for SFSafariExtension {}
);

impl SFSafariExtension {
    extern_methods!(
        // +new (unavailable)

        // -init (unavailable)

        #[cfg(feature = "block2")]
        /// Calls the completion handler with the base URI of the extension.
        #[unsafe(method(getBaseURIWithCompletionHandler:))]
        #[unsafe(method_family = none)]
        pub unsafe fn getBaseURIWithCompletionHandler(
            completion_handler: &block2::DynBlock<dyn Fn(*mut NSURL)>,
        );
    );
}
