#[cfg(feature = "Accessibility")]
pub mod Accessibility;
#[cfg(feature = "AdServices")]
pub mod AdServices;
#[cfg(feature = "AdSupport")]
pub mod AdSupport;
#[cfg(feature = "AppKit")]
pub mod AppKit;
#[cfg(feature = "AuthenticationServices")]
pub mod AuthenticationServices;
#[cfg(feature = "AutomaticAssessmentConfiguration")]
pub mod AutomaticAssessmentConfiguration;
#[cfg(feature = "Automator")]
pub mod Automator;
#[cfg(feature = "BackgroundAssets")]
pub mod BackgroundAssets;
#[cfg(feature = "BackgroundTasks")]
pub mod BackgroundTasks;
#[cfg(feature = "BusinessChat")]
pub mod BusinessChat;
#[cfg(feature = "CallKit")]
pub mod CallKit;
#[cfg(feature = "ClassKit")]
pub mod ClassKit;
#[cfg(feature = "CloudKit")]
pub mod CloudKit;
#[cfg(feature = "Contacts")]
pub mod Contacts;
#[cfg(feature = "CoreData")]
pub mod CoreData;
#[cfg(feature = "CoreLocation")]
pub mod CoreLocation;
#[cfg(feature = "CoreWLAN")]
pub mod CoreWLAN;
#[cfg(feature = "DataDetection")]
pub mod DataDetection;
#[cfg(feature = "DeviceCheck")]
pub mod DeviceCheck;
#[cfg(feature = "EventKit")]
pub mod EventKit;
#[cfg(feature = "ExceptionHandling")]
pub mod ExceptionHandling;
#[cfg(feature = "ExtensionKit")]
pub mod ExtensionKit;
#[cfg(feature = "ExternalAccessory")]
pub mod ExternalAccessory;
#[cfg(feature = "FileProvider")]
pub mod FileProvider;
#[cfg(feature = "FileProviderUI")]
pub mod FileProviderUI;
#[cfg(feature = "Foundation")]
pub mod Foundation;
#[cfg(feature = "GameController")]
pub mod GameController;
#[cfg(feature = "GameKit")]
pub mod GameKit;
#[cfg(feature = "HealthKit")]
pub mod HealthKit;
#[cfg(feature = "IdentityLookup")]
pub mod IdentityLookup;
#[cfg(feature = "InputMethodKit")]
pub mod InputMethodKit;
#[cfg(feature = "LinkPresentation")]
pub mod LinkPresentation;
#[cfg(feature = "LocalAuthentication")]
pub mod LocalAuthentication;
#[cfg(feature = "LocalAuthenticationEmbeddedUI")]
pub mod LocalAuthenticationEmbeddedUI;
#[cfg(feature = "MailKit")]
pub mod MailKit;
#[cfg(feature = "MapKit")]
pub mod MapKit;
#[cfg(feature = "MediaPlayer")]
pub mod MediaPlayer;
#[cfg(feature = "Metal")]
pub mod Metal;
#[cfg(feature = "MetalFX")]
pub mod MetalFX;
#[cfg(feature = "MetalKit")]
pub mod MetalKit;
#[cfg(feature = "MetricKit")]
pub mod MetricKit;
#[cfg(feature = "OSAKit")]
pub mod OSAKit;
#[cfg(feature = "Photos")]
pub mod Photos;
#[cfg(feature = "QuartzCore")]
pub mod QuartzCore;
#[cfg(feature = "SoundAnalysis")]
pub mod SoundAnalysis;
#[cfg(feature = "Speech")]
pub mod Speech;
#[cfg(feature = "StoreKit")]
pub mod StoreKit;
#[cfg(feature = "UniformTypeIdentifiers")]
pub mod UniformTypeIdentifiers;
#[cfg(feature = "UserNotifications")]
pub mod UserNotifications;
#[cfg(feature = "WebKit")]
pub mod WebKit;
