//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::Foundation::*;
use crate::WebKit::*;

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(all(feature = "WebKit_DOMObject", feature = "WebKit_WebScriptObject"))]
    #[deprecated]
    pub struct DOMRect;

    #[cfg(all(feature = "WebKit_DOMObject", feature = "WebKit_WebScriptObject"))]
    unsafe impl ClassType for DOMRect {
        #[inherits(WebScriptObject, NSObject)]
        type Super = DOMObject;
        type Mutability = InteriorMutable;
    }
);

#[cfg(all(
    feature = "Foundation_NSObject",
    feature = "WebKit_DOMObject",
    feature = "WebKit_WebScriptObject"
))]
unsafe impl NSCopying for DOMRect {}

#[cfg(all(feature = "WebKit_DOMObject", feature = "WebKit_WebScriptObject"))]
unsafe impl NSObjectProtocol for DOMRect {}

extern_methods!(
    #[cfg(all(feature = "WebKit_DOMObject", feature = "WebKit_WebScriptObject"))]
    unsafe impl DOMRect {
        #[cfg(all(
            feature = "WebKit_DOMCSSPrimitiveValue",
            feature = "WebKit_DOMCSSValue"
        ))]
        #[deprecated]
        #[method_id(@__retain_semantics Other top)]
        pub unsafe fn top(&self) -> Option<Id<DOMCSSPrimitiveValue>>;

        #[cfg(all(
            feature = "WebKit_DOMCSSPrimitiveValue",
            feature = "WebKit_DOMCSSValue"
        ))]
        #[deprecated]
        #[method_id(@__retain_semantics Other right)]
        pub unsafe fn right(&self) -> Option<Id<DOMCSSPrimitiveValue>>;

        #[cfg(all(
            feature = "WebKit_DOMCSSPrimitiveValue",
            feature = "WebKit_DOMCSSValue"
        ))]
        #[deprecated]
        #[method_id(@__retain_semantics Other bottom)]
        pub unsafe fn bottom(&self) -> Option<Id<DOMCSSPrimitiveValue>>;

        #[cfg(all(
            feature = "WebKit_DOMCSSPrimitiveValue",
            feature = "WebKit_DOMCSSValue"
        ))]
        #[deprecated]
        #[method_id(@__retain_semantics Other left)]
        pub unsafe fn left(&self) -> Option<Id<DOMCSSPrimitiveValue>>;
    }
);

extern_methods!(
    /// Methods declared on superclass `DOMObject`
    #[cfg(all(feature = "WebKit_DOMObject", feature = "WebKit_WebScriptObject"))]
    unsafe impl DOMRect {
        #[deprecated]
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Id<Self>;
    }
);

extern_methods!(
    /// Methods declared on superclass `NSObject`
    #[cfg(all(feature = "WebKit_DOMObject", feature = "WebKit_WebScriptObject"))]
    unsafe impl DOMRect {
        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Id<Self>;
    }
);
