//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use core::ffi::*;
use core::ptr::NonNull;
use objc2::__framework_prelude::*;
use objc2_foundation::*;

use crate::*;

extern_class!(
    /// A WKContentWorldConfiguration object allows you to specify custom behavior for a WKContentWorld instance.
    ///
    /// WKContentWorldConfiguration allows applications to create WKContentWorld instances which have extra JavaScript
    /// capabilities exposed to script in their environment. It does not change any default WebKit behaviors, nor change anything that web page
    /// JavaScript can do. Only application JavaScript run in the created `WKContentWorld` will have different capabilities.
    ///
    /// For example:
    /// - If your scripts help provide autofill capabilities, you would want to set autofillEnabled to YES.
    ///
    /// See also [Apple's documentation](https://developer.apple.com/documentation/webkit/wkcontentworldconfiguration?language=objc)
    #[unsafe(super(NSObject))]
    #[thread_kind = MainThreadOnly]
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub struct WKContentWorldConfiguration;
);

extern_conformance!(
    unsafe impl NSCoding for WKContentWorldConfiguration {}
);

extern_conformance!(
    unsafe impl NSCopying for WKContentWorldConfiguration {}
);

unsafe impl CopyingHelper for WKContentWorldConfiguration {
    type Result = Self;
}

extern_conformance!(
    unsafe impl NSObjectProtocol for WKContentWorldConfiguration {}
);

extern_conformance!(
    unsafe impl NSSecureCoding for WKContentWorldConfiguration {}
);

impl WKContentWorldConfiguration {
    extern_methods!(
        /// A boolean value indicating whether every shadow root should be treated as open mode shadow root or not.
        #[unsafe(method(openClosedShadowRootsEnabled))]
        #[unsafe(method_family = none)]
        pub unsafe fn openClosedShadowRootsEnabled(&self) -> bool;

        /// Setter for [`openClosedShadowRootsEnabled`][Self::openClosedShadowRootsEnabled].
        #[unsafe(method(setOpenClosedShadowRootsEnabled:))]
        #[unsafe(method_family = none)]
        pub unsafe fn setOpenClosedShadowRootsEnabled(
            &self,
            open_closed_shadow_roots_enabled: bool,
        );

        /// A boolean value indicating whether the capability to trigger autofill is exposed to scripts or not.
        #[unsafe(method(autofillScriptingEnabled))]
        #[unsafe(method_family = none)]
        pub unsafe fn autofillScriptingEnabled(&self) -> bool;

        /// Setter for [`autofillScriptingEnabled`][Self::autofillScriptingEnabled].
        #[unsafe(method(setAutofillScriptingEnabled:))]
        #[unsafe(method_family = none)]
        pub unsafe fn setAutofillScriptingEnabled(&self, autofill_scripting_enabled: bool);

        /// A boolean value indicating whether the ability to attach user info on an element is exposed to scripts or not.
        #[unsafe(method(elementUserInfoEnabled))]
        #[unsafe(method_family = none)]
        pub unsafe fn elementUserInfoEnabled(&self) -> bool;

        /// Setter for [`elementUserInfoEnabled`][Self::elementUserInfoEnabled].
        #[unsafe(method(setElementUserInfoEnabled:))]
        #[unsafe(method_family = none)]
        pub unsafe fn setElementUserInfoEnabled(&self, element_user_info_enabled: bool);

        /// A boolean value indicating whether the behavior that elements with a name attribute overrides builtin methods on document object should be enabled or not.
        #[unsafe(method(legacyBuiltinOverridesEnabled))]
        #[unsafe(method_family = none)]
        pub unsafe fn legacyBuiltinOverridesEnabled(&self) -> bool;

        /// Setter for [`legacyBuiltinOverridesEnabled`][Self::legacyBuiltinOverridesEnabled].
        #[unsafe(method(setLegacyBuiltinOverridesEnabled:))]
        #[unsafe(method_family = none)]
        pub unsafe fn setLegacyBuiltinOverridesEnabled(
            &self,
            legacy_builtin_overrides_enabled: bool,
        );

        /// A boolean indicating whether or not `window.webkit.serializeNode` is available.
        ///
        /// JavaScript can call `window.webkit.serializeNode` with a return value to create a `WKJSSerializedNode`
        /// object for the application to use in future JavaScript programs.
        /// Refer to the `WKJSSerializedNode` documentation for more information.
        #[unsafe(method(nodeSerializationEnabled))]
        #[unsafe(method_family = none)]
        pub unsafe fn nodeSerializationEnabled(&self) -> bool;

        /// Setter for [`nodeSerializationEnabled`][Self::nodeSerializationEnabled].
        #[unsafe(method(setNodeSerializationEnabled:))]
        #[unsafe(method_family = none)]
        pub unsafe fn setNodeSerializationEnabled(&self, node_serialization_enabled: bool);

        /// A boolean indicating whether or not `window.webkit.createJSHandle` is available.
        #[unsafe(method(jsHandleCreationEnabled))]
        #[unsafe(method_family = none)]
        pub unsafe fn jsHandleCreationEnabled(&self) -> bool;

        /// Setter for [`jsHandleCreationEnabled`][Self::jsHandleCreationEnabled].
        #[unsafe(method(setJSHandleCreationEnabled:))]
        #[unsafe(method_family = none)]
        pub unsafe fn setJSHandleCreationEnabled(&self, js_handle_creation_enabled: bool);

        /// A boolean indicating whether the JavaScript in this world is visible to the Web Inspector.
        #[unsafe(method(isInspectable))]
        #[unsafe(method_family = none)]
        pub unsafe fn isInspectable(&self) -> bool;

        /// Setter for [`isInspectable`][Self::isInspectable].
        #[unsafe(method(setInspectable:))]
        #[unsafe(method_family = none)]
        pub unsafe fn setInspectable(&self, inspectable: bool);
    );
}

/// Methods declared on superclass `NSObject`.
impl WKContentWorldConfiguration {
    extern_methods!(
        #[unsafe(method(init))]
        #[unsafe(method_family = init)]
        pub unsafe fn init(this: Allocated<Self>) -> Retained<Self>;

        #[unsafe(method(new))]
        #[unsafe(method_family = new)]
        pub unsafe fn new(mtm: MainThreadMarker) -> Retained<Self>;
    );
}
