//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::Foundation;
use crate::Metal;

ns_options!(
    #[underlying(NSUInteger)]
    pub enum MTLResourceUsage {
        MTLResourceUsageRead = 1 << 0,
        MTLResourceUsageWrite = 1 << 1,
        MTLResourceUsageSample = 1 << 2,
    }
);

ns_options!(
    #[underlying(NSUInteger)]
    pub enum MTLBarrierScope {
        MTLBarrierScopeBuffers = 1 << 0,
        MTLBarrierScopeTextures = 1 << 1,
        MTLBarrierScopeRenderTargets = 1 << 2,
    }
);

extern_protocol!(
    pub struct MTLCommandEncoder;

    unsafe impl ProtocolType for MTLCommandEncoder {
        #[method_id(@__retain_semantics Other device)]
        pub unsafe fn device(&self) -> Id<Metal::MTLDevice, Shared>;

        #[method_id(@__retain_semantics Other label)]
        pub fn label(&self) -> Option<Id<Foundation::NSString, Shared>>;

        #[method(setLabel:)]
        pub fn setLabel(&self, label: Option<&Foundation::NSString>);

        #[method(endEncoding)]
        pub fn endEncoding(&self);

        #[method(insertDebugSignpost:)]
        pub fn insertDebugSignpost(&self, string: &Foundation::NSString);

        #[method(pushDebugGroup:)]
        pub fn pushDebugGroup(&self, string: &Foundation::NSString);

        #[method(popDebugGroup)]
        pub fn popDebugGroup(&self);
    }
);
