//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::Foundation::*;
use crate::Speech::*;

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub struct SFAcousticFeature;

    unsafe impl ClassType for SFAcousticFeature {
        type Super = NSObject;
        type Mutability = InteriorMutable;
    }
);

#[cfg(feature = "Foundation_NSObject")]
unsafe impl NSCoding for SFAcousticFeature {}

#[cfg(feature = "Foundation_NSObject")]
unsafe impl NSCopying for SFAcousticFeature {}

unsafe impl NSObjectProtocol for SFAcousticFeature {}

#[cfg(feature = "Foundation_NSObject")]
unsafe impl NSSecureCoding for SFAcousticFeature {}

extern_methods!(
    unsafe impl SFAcousticFeature {
        #[cfg(all(feature = "Foundation_NSArray", feature = "Foundation_NSValue"))]
        #[method_id(@__retain_semantics Other acousticFeatureValuePerFrame)]
        pub unsafe fn acousticFeatureValuePerFrame(&self) -> Id<NSArray<NSNumber>>;

        #[cfg(feature = "Foundation_NSDate")]
        #[method(frameDuration)]
        pub unsafe fn frameDuration(&self) -> NSTimeInterval;
    }
);

extern_methods!(
    /// Methods declared on superclass `NSObject`
    unsafe impl SFAcousticFeature {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Id<Self>;

        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Id<Self>;
    }
);

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub struct SFVoiceAnalytics;

    unsafe impl ClassType for SFVoiceAnalytics {
        type Super = NSObject;
        type Mutability = InteriorMutable;
    }
);

#[cfg(feature = "Foundation_NSObject")]
unsafe impl NSCoding for SFVoiceAnalytics {}

#[cfg(feature = "Foundation_NSObject")]
unsafe impl NSCopying for SFVoiceAnalytics {}

unsafe impl NSObjectProtocol for SFVoiceAnalytics {}

#[cfg(feature = "Foundation_NSObject")]
unsafe impl NSSecureCoding for SFVoiceAnalytics {}

extern_methods!(
    unsafe impl SFVoiceAnalytics {
        #[method_id(@__retain_semantics Other jitter)]
        pub unsafe fn jitter(&self) -> Id<SFAcousticFeature>;

        #[method_id(@__retain_semantics Other shimmer)]
        pub unsafe fn shimmer(&self) -> Id<SFAcousticFeature>;

        #[method_id(@__retain_semantics Other pitch)]
        pub unsafe fn pitch(&self) -> Id<SFAcousticFeature>;

        #[method_id(@__retain_semantics Other voicing)]
        pub unsafe fn voicing(&self) -> Id<SFAcousticFeature>;
    }
);

extern_methods!(
    /// Methods declared on superclass `NSObject`
    unsafe impl SFVoiceAnalytics {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Id<Self>;

        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Id<Self>;
    }
);
