//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use core::ptr::NonNull;
use objc2::__framework_prelude::*;
use objc2_foundation::*;

use crate::*;

extern_protocol!(
    /// [Apple's documentation](https://developer.apple.com/documentation/coreml/mlfeatureprovider?language=objc)
    pub unsafe trait MLFeatureProvider {
        #[method_id(@__method_family Other featureNames)]
        unsafe fn featureNames(&self) -> Retained<NSSet<NSString>>;

        #[cfg(feature = "MLFeatureValue")]
        /// Returns nil if the provided featureName is not in the set of featureNames
        #[method_id(@__method_family Other featureValueForName:)]
        unsafe fn featureValueForName(
            &self,
            feature_name: &NSString,
        ) -> Option<Retained<MLFeatureValue>>;
    }
);
