//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use core::ptr::NonNull;
use objc2::__framework_prelude::*;
use objc2_foundation::*;

use crate::*;

extern_class!(
    /// [Apple's documentation](https://developer.apple.com/documentation/callkit/cxcall?language=objc)
    #[unsafe(super(NSObject))]
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub struct CXCall;
);

unsafe impl NSObjectProtocol for CXCall {}

extern_methods!(
    unsafe impl CXCall {
        #[unsafe(method_family(none))]
        #[method_id(UUID)]
        pub unsafe fn UUID(&self) -> Retained<NSUUID>;

        #[method(isOutgoing)]
        pub unsafe fn isOutgoing(&self) -> bool;

        #[method(isOnHold)]
        pub unsafe fn isOnHold(&self) -> bool;

        #[method(hasConnected)]
        pub unsafe fn hasConnected(&self) -> bool;

        #[method(hasEnded)]
        pub unsafe fn hasEnded(&self) -> bool;

        #[unsafe(method_family(init))]
        #[method_id(init)]
        pub unsafe fn init(this: Allocated<Self>) -> Retained<Self>;

        #[method(isEqualToCall:)]
        pub unsafe fn isEqualToCall(&self, call: &CXCall) -> bool;
    }
);

extern_methods!(
    /// Methods declared on superclass `NSObject`
    unsafe impl CXCall {
        #[unsafe(method_family(new))]
        #[method_id(new)]
        pub unsafe fn new() -> Retained<Self>;
    }
);
