//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use core::ffi::*;
use core::ptr::NonNull;
use objc2::__framework_prelude::*;
use objc2_foundation::*;

use crate::*;

extern_class!(
    /// [Apple's documentation](https://developer.apple.com/documentation/multipeerconnectivity/mcnearbyservicebrowser?language=objc)
    #[unsafe(super(NSObject))]
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub struct MCNearbyServiceBrowser;
);

unsafe impl NSObjectProtocol for MCNearbyServiceBrowser {}

extern_methods!(
    unsafe impl MCNearbyServiceBrowser {
        #[cfg(feature = "MCPeerID")]
        #[unsafe(method_family(init))]
        #[method_id(initWithPeer:serviceType:)]
        pub unsafe fn initWithPeer_serviceType(
            this: Allocated<Self>,
            my_peer_id: &MCPeerID,
            service_type: &NSString,
        ) -> Retained<Self>;

        #[method(startBrowsingForPeers)]
        pub unsafe fn startBrowsingForPeers(&self);

        #[method(stopBrowsingForPeers)]
        pub unsafe fn stopBrowsingForPeers(&self);

        #[cfg(all(feature = "MCPeerID", feature = "MCSession"))]
        #[method(invitePeer:toSession:withContext:timeout:)]
        pub unsafe fn invitePeer_toSession_withContext_timeout(
            &self,
            peer_id: &MCPeerID,
            session: &MCSession,
            context: Option<&NSData>,
            timeout: NSTimeInterval,
        );

        #[unsafe(method_family(none))]
        #[method_id(delegate)]
        pub unsafe fn delegate(
            &self,
        ) -> Option<Retained<ProtocolObject<dyn MCNearbyServiceBrowserDelegate>>>;

        /// This is a [weak property][objc2::topics::weak_property].
        /// Setter for [`delegate`][Self::delegate].
        #[method(setDelegate:)]
        pub unsafe fn setDelegate(
            &self,
            delegate: Option<&ProtocolObject<dyn MCNearbyServiceBrowserDelegate>>,
        );

        #[cfg(feature = "MCPeerID")]
        #[unsafe(method_family(none))]
        #[method_id(myPeerID)]
        pub unsafe fn myPeerID(&self) -> Retained<MCPeerID>;

        #[unsafe(method_family(none))]
        #[method_id(serviceType)]
        pub unsafe fn serviceType(&self) -> Retained<NSString>;
    }
);

extern_methods!(
    /// Methods declared on superclass `NSObject`
    unsafe impl MCNearbyServiceBrowser {
        #[unsafe(method_family(init))]
        #[method_id(init)]
        pub unsafe fn init(this: Allocated<Self>) -> Retained<Self>;

        #[unsafe(method_family(new))]
        #[method_id(new)]
        pub unsafe fn new() -> Retained<Self>;
    }
);

extern_protocol!(
    /// [Apple's documentation](https://developer.apple.com/documentation/multipeerconnectivity/mcnearbyservicebrowserdelegate?language=objc)
    pub unsafe trait MCNearbyServiceBrowserDelegate: NSObjectProtocol {
        #[cfg(feature = "MCPeerID")]
        #[method(browser:foundPeer:withDiscoveryInfo:)]
        unsafe fn browser_foundPeer_withDiscoveryInfo(
            &self,
            browser: &MCNearbyServiceBrowser,
            peer_id: &MCPeerID,
            info: Option<&NSDictionary<NSString, NSString>>,
        );

        #[cfg(feature = "MCPeerID")]
        #[method(browser:lostPeer:)]
        unsafe fn browser_lostPeer(&self, browser: &MCNearbyServiceBrowser, peer_id: &MCPeerID);

        #[optional]
        #[method(browser:didNotStartBrowsingForPeers:)]
        unsafe fn browser_didNotStartBrowsingForPeers(
            &self,
            browser: &MCNearbyServiceBrowser,
            error: &NSError,
        );
    }
);
