//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use core::ffi::*;
use core::ptr::NonNull;
use objc2::__framework_prelude::*;

use crate::*;

extern_class!(
    /// [Apple's documentation](https://developer.apple.com/documentation/uikit/uitextinputcontext?language=objc)
    #[unsafe(super(NSObject))]
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub struct UITextInputContext;
);

unsafe impl NSObjectProtocol for UITextInputContext {}

extern_methods!(
    unsafe impl UITextInputContext {
        #[method(isPencilInputExpected)]
        pub unsafe fn isPencilInputExpected(&self) -> bool;

        /// Setter for [`isPencilInputExpected`][Self::isPencilInputExpected].
        #[method(setPencilInputExpected:)]
        pub unsafe fn setPencilInputExpected(&self, pencil_input_expected: bool);

        #[method(isDictationInputExpected)]
        pub unsafe fn isDictationInputExpected(&self) -> bool;

        /// Setter for [`isDictationInputExpected`][Self::isDictationInputExpected].
        #[method(setDictationInputExpected:)]
        pub unsafe fn setDictationInputExpected(&self, dictation_input_expected: bool);

        #[method(isHardwareKeyboardInputExpected)]
        pub unsafe fn isHardwareKeyboardInputExpected(&self) -> bool;

        /// Setter for [`isHardwareKeyboardInputExpected`][Self::isHardwareKeyboardInputExpected].
        #[method(setHardwareKeyboardInputExpected:)]
        pub unsafe fn setHardwareKeyboardInputExpected(
            &self,
            hardware_keyboard_input_expected: bool,
        );

        #[unsafe(method_family(init))]
        #[method_id(init)]
        pub unsafe fn init(this: Allocated<Self>) -> Retained<Self>;

        #[unsafe(method_family(new))]
        #[method_id(new)]
        pub unsafe fn new() -> Retained<Self>;

        #[unsafe(method_family(none))]
        #[method_id(current)]
        pub unsafe fn current() -> Option<Retained<UITextInputContext>>;
    }
);
