// This file has been automatically generated by `objc2`'s `header-translator`.
// DO NOT EDIT

#![allow(unused_imports)]
#![allow(deprecated)]
#![allow(non_snake_case)]
#![allow(non_camel_case_types)]
#![allow(non_upper_case_globals)]
#![allow(missing_docs)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::type_complexity)]
#![allow(clippy::new_ret_no_self)]
#![allow(clippy::upper_case_acronyms)]
#![allow(clippy::identity_op)]
#![allow(clippy::missing_safety_doc)]
#![allow(clippy::doc_lazy_continuation)]
#![allow(rustdoc::broken_intra_doc_links)]
#![allow(rustdoc::bare_urls)]
#![allow(rustdoc::invalid_html_tags)]

#[link(name = "AutomaticAssessmentConfiguration", kind = "framework")]
extern "C" {}

use core::ffi::*;
use core::ptr::NonNull;
use objc2::__framework_prelude::*;
use objc2_foundation::*;

use crate::*;

/// Identifies an item in the Apple menu.
///
/// Use these constants with ``AEAssessmentConfiguration/allowedAppleMenuItems``
/// to control which Apple menu items are visible during an assessment session.
///
/// - Note: ``AEAppleMenuItemAboutThisMac`` is always visible during assessment
/// sessions regardless of configuration.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/automaticassessmentconfiguration/aeapplemenuitem?language=objc)
// NS_TYPED_ENUM
pub type AEAppleMenuItem = NSString;

extern "C" {
    /// [Apple's documentation](https://developer.apple.com/documentation/automaticassessmentconfiguration/aeapplemenuitemaboutthismac?language=objc)
    pub static AEAppleMenuItemAboutThisMac: &'static AEAppleMenuItem;
}

extern "C" {
    /// [Apple's documentation](https://developer.apple.com/documentation/automaticassessmentconfiguration/aeapplemenuitemappstore?language=objc)
    pub static AEAppleMenuItemAppStore: &'static AEAppleMenuItem;
}

extern "C" {
    /// [Apple's documentation](https://developer.apple.com/documentation/automaticassessmentconfiguration/aeapplemenuitemforcequit?language=objc)
    pub static AEAppleMenuItemForceQuit: &'static AEAppleMenuItem;
}

extern "C" {
    /// [Apple's documentation](https://developer.apple.com/documentation/automaticassessmentconfiguration/aeapplemenuitemlocation?language=objc)
    pub static AEAppleMenuItemLocation: &'static AEAppleMenuItem;
}

extern "C" {
    /// [Apple's documentation](https://developer.apple.com/documentation/automaticassessmentconfiguration/aeapplemenuitemlockscreen?language=objc)
    pub static AEAppleMenuItemLockScreen: &'static AEAppleMenuItem;
}

extern "C" {
    /// [Apple's documentation](https://developer.apple.com/documentation/automaticassessmentconfiguration/aeapplemenuitemlogout?language=objc)
    pub static AEAppleMenuItemLogout: &'static AEAppleMenuItem;
}

extern "C" {
    /// [Apple's documentation](https://developer.apple.com/documentation/automaticassessmentconfiguration/aeapplemenuitemrecent?language=objc)
    pub static AEAppleMenuItemRecent: &'static AEAppleMenuItem;
}

extern "C" {
    /// [Apple's documentation](https://developer.apple.com/documentation/automaticassessmentconfiguration/aeapplemenuitemrestart?language=objc)
    pub static AEAppleMenuItemRestart: &'static AEAppleMenuItem;
}

extern "C" {
    /// [Apple's documentation](https://developer.apple.com/documentation/automaticassessmentconfiguration/aeapplemenuitemshutdown?language=objc)
    pub static AEAppleMenuItemShutDown: &'static AEAppleMenuItem;
}

extern "C" {
    /// [Apple's documentation](https://developer.apple.com/documentation/automaticassessmentconfiguration/aeapplemenuitemsleep?language=objc)
    pub static AEAppleMenuItemSleep: &'static AEAppleMenuItem;
}

extern "C" {
    /// [Apple's documentation](https://developer.apple.com/documentation/automaticassessmentconfiguration/aeapplemenuitemsysteminformation?language=objc)
    pub static AEAppleMenuItemSystemInformation: &'static AEAppleMenuItem;
}

extern "C" {
    /// [Apple's documentation](https://developer.apple.com/documentation/automaticassessmentconfiguration/aeapplemenuitemsystemsettings?language=objc)
    pub static AEAppleMenuItemSystemSettings: &'static AEAppleMenuItem;
}

extern_class!(
    /// [Apple's documentation](https://developer.apple.com/documentation/automaticassessmentconfiguration/aeassessmentapplication?language=objc)
    #[unsafe(super(NSObject))]
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub struct AEAssessmentApplication;
);

extern_conformance!(
    unsafe impl NSCopying for AEAssessmentApplication {}
);

unsafe impl CopyingHelper for AEAssessmentApplication {
    type Result = Self;
}

extern_conformance!(
    unsafe impl NSObjectProtocol for AEAssessmentApplication {}
);

impl AEAssessmentApplication {
    extern_methods!(
        #[unsafe(method(bundleIdentifier))]
        #[unsafe(method_family = none)]
        pub unsafe fn bundleIdentifier(&self) -> Retained<NSString>;

        #[unsafe(method(teamIdentifier))]
        #[unsafe(method_family = none)]
        pub unsafe fn teamIdentifier(&self) -> Option<Retained<NSString>>;

        #[unsafe(method(requiresSignatureValidation))]
        #[unsafe(method_family = none)]
        pub unsafe fn requiresSignatureValidation(&self) -> bool;

        /// Setter for [`requiresSignatureValidation`][Self::requiresSignatureValidation].
        #[unsafe(method(setRequiresSignatureValidation:))]
        #[unsafe(method_family = none)]
        pub unsafe fn setRequiresSignatureValidation(&self, requires_signature_validation: bool);

        #[unsafe(method(initWithBundleIdentifier:))]
        #[unsafe(method_family = init)]
        pub unsafe fn initWithBundleIdentifier(
            this: Allocated<Self>,
            bundle_identifier: &NSString,
        ) -> Retained<Self>;

        #[unsafe(method(initWithBundleIdentifier:teamIdentifier:))]
        #[unsafe(method_family = init)]
        pub unsafe fn initWithBundleIdentifier_teamIdentifier(
            this: Allocated<Self>,
            bundle_identifier: &NSString,
            team_identifier: Option<&NSString>,
        ) -> Retained<Self>;
    );
}

extern_class!(
    /// A non-bundled, non-UI executable (e.g. a launchd daemon) designated as an assessment participant
    /// by its on-disk path.
    ///
    /// Use this for a participant that has no bundle identifier and so cannot be expressed as an
    /// ``AEAssessmentApplication``. It feeds only the app-launch allowlist under
    /// ``AEAssessmentConfiguration/allowOnlyParticipantsToRun`` and, when its configuration permits,
    /// network access; UI policies (frontmost app, window server, media, menu bar) do not apply.
    ///
    /// Matching is by exact on-disk path. At runtime the executable must also satisfy
    /// ``requiresSignatureValidation`` (and the team identifier, if set), so a swapped or re-signed
    /// binary is not silently trusted. Leave ``requiresSignatureValidation`` enabled (the default)
    /// unless the executable is unsigned.
    ///
    /// - SeeAlso: ``AEAssessmentApplication`` for bundled participants.
    ///
    /// See also [Apple's documentation](https://developer.apple.com/documentation/automaticassessmentconfiguration/aeassessmentbinaryexecutable?language=objc)
    #[unsafe(super(NSObject))]
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub struct AEAssessmentBinaryExecutable;
);

extern_conformance!(
    unsafe impl NSCopying for AEAssessmentBinaryExecutable {}
);

unsafe impl CopyingHelper for AEAssessmentBinaryExecutable {
    type Result = Self;
}

extern_conformance!(
    unsafe impl NSObjectProtocol for AEAssessmentBinaryExecutable {}
);

impl AEAssessmentBinaryExecutable {
    extern_methods!(
        /// On-disk path of the executable.
        #[unsafe(method(binaryExecutableURL))]
        #[unsafe(method_family = none)]
        pub unsafe fn binaryExecutableURL(&self) -> Retained<NSURL>;

        /// Team identifier the running executable's signature must match, or `nil` to skip the team check.
        #[unsafe(method(teamIdentifier))]
        #[unsafe(method_family = none)]
        pub unsafe fn teamIdentifier(&self) -> Option<Retained<NSString>>;

        /// Whether the running executable's code signature is validated. Defaults to `YES`.
        #[unsafe(method(requiresSignatureValidation))]
        #[unsafe(method_family = none)]
        pub unsafe fn requiresSignatureValidation(&self) -> bool;

        /// Setter for [`requiresSignatureValidation`][Self::requiresSignatureValidation].
        #[unsafe(method(setRequiresSignatureValidation:))]
        #[unsafe(method_family = none)]
        pub unsafe fn setRequiresSignatureValidation(&self, requires_signature_validation: bool);

        #[unsafe(method(initWithBinaryExecutableURL:))]
        #[unsafe(method_family = init)]
        pub unsafe fn initWithBinaryExecutableURL(
            this: Allocated<Self>,
            binary_executable_url: &NSURL,
        ) -> Retained<Self>;

        #[unsafe(method(initWithBinaryExecutableURL:teamIdentifier:))]
        #[unsafe(method_family = init)]
        pub unsafe fn initWithBinaryExecutableURL_teamIdentifier(
            this: Allocated<Self>,
            binary_executable_url: &NSURL,
            team_identifier: Option<&NSString>,
        ) -> Retained<Self>;
    );
}

extern_class!(
    /// The configuration applied to an ``AEAssessmentBinaryExecutable`` participant.
    ///
    /// A non-bundled executable (such as a launchd daemon) is headless, so it supports only the subset of
    /// participant policies that apply to a process without UI: network access and whether the assessment
    /// requires it. The UI-oriented policies of ``AEAssessmentParticipantConfiguration`` (allowed menu items,
    /// graceful termination) do not apply.
    ///
    /// - SeeAlso: ``AEAssessmentBinaryExecutable``, ``AEAssessmentParticipantConfiguration``.
    ///
    /// See also [Apple's documentation](https://developer.apple.com/documentation/automaticassessmentconfiguration/aeassessmentbinaryexecutableconfiguration?language=objc)
    #[unsafe(super(NSObject))]
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub struct AEAssessmentBinaryExecutableConfiguration;
);

extern_conformance!(
    unsafe impl NSCopying for AEAssessmentBinaryExecutableConfiguration {}
);

unsafe impl CopyingHelper for AEAssessmentBinaryExecutableConfiguration {
    type Result = Self;
}

extern_conformance!(
    unsafe impl NSObjectProtocol for AEAssessmentBinaryExecutableConfiguration {}
);

impl AEAssessmentBinaryExecutableConfiguration {
    extern_methods!(
        /// Whether the executable may access the network during an assessment. Defaults to `YES`.
        #[unsafe(method(allowsNetworkAccess))]
        #[unsafe(method_family = none)]
        pub unsafe fn allowsNetworkAccess(&self) -> bool;

        /// Setter for [`allowsNetworkAccess`][Self::allowsNetworkAccess].
        #[unsafe(method(setAllowsNetworkAccess:))]
        #[unsafe(method_family = none)]
        pub unsafe fn setAllowsNetworkAccess(&self, allows_network_access: bool);

        /// Whether the assessment requires this executable. Defaults to `NO`.
        #[unsafe(method(isRequired))]
        #[unsafe(method_family = none)]
        pub unsafe fn isRequired(&self) -> bool;

        /// Setter for [`isRequired`][Self::isRequired].
        #[unsafe(method(setRequired:))]
        #[unsafe(method_family = none)]
        pub unsafe fn setRequired(&self, required: bool);

        #[unsafe(method(init))]
        #[unsafe(method_family = init)]
        pub unsafe fn init(this: Allocated<Self>) -> Retained<Self>;

        #[unsafe(method(new))]
        #[unsafe(method_family = new)]
        pub unsafe fn new() -> Retained<Self>;
    );
}

/// [Apple's documentation](https://developer.apple.com/documentation/automaticassessmentconfiguration/aemenubaritem?language=objc)
// NS_TYPED_EXTENSIBLE_ENUM
pub type AEMenuBarItem = NSString;

extern "C" {
    /// [Apple's documentation](https://developer.apple.com/documentation/automaticassessmentconfiguration/aemenubaritembattery?language=objc)
    pub static AEMenuBarItemBattery: &'static AEMenuBarItem;
}

extern "C" {
    /// [Apple's documentation](https://developer.apple.com/documentation/automaticassessmentconfiguration/aemenubaritembluetooth?language=objc)
    pub static AEMenuBarItemBluetooth: &'static AEMenuBarItem;
}

extern "C" {
    /// [Apple's documentation](https://developer.apple.com/documentation/automaticassessmentconfiguration/aemenubaritemclock?language=objc)
    pub static AEMenuBarItemClock: &'static AEMenuBarItem;
}

extern "C" {
    /// [Apple's documentation](https://developer.apple.com/documentation/automaticassessmentconfiguration/aemenubaritemdisplays?language=objc)
    pub static AEMenuBarItemDisplays: &'static AEMenuBarItem;
}

extern "C" {
    /// [Apple's documentation](https://developer.apple.com/documentation/automaticassessmentconfiguration/aemenubaritemkeyboard?language=objc)
    pub static AEMenuBarItemKeyboard: &'static AEMenuBarItem;
}

extern "C" {
    /// [Apple's documentation](https://developer.apple.com/documentation/automaticassessmentconfiguration/aemenubaritemvolume?language=objc)
    pub static AEMenuBarItemVolume: &'static AEMenuBarItem;
}

extern "C" {
    /// [Apple's documentation](https://developer.apple.com/documentation/automaticassessmentconfiguration/aemenubaritemwifi?language=objc)
    pub static AEMenuBarItemWifi: &'static AEMenuBarItem;
}

/// Specifies the type of account required for an assessment session.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/automaticassessmentconfiguration/aeuseraccounttype?language=objc)
// NS_CLOSED_ENUM
#[repr(isize)] // NSInteger
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, Default)]
pub enum AEUserAccountType {
    /// No specific account type is required.
    #[doc(alias = "AEUserAccountTypeAny")]
    #[default]
    Any = 0,
    /// Requires a standard user account.
    #[doc(alias = "AEUserAccountTypeStandard")]
    Standard = 1,
    /// Requires a guest user account.
    #[doc(alias = "AEUserAccountTypeGuest")]
    Guest = 2,
}

unsafe impl Encode for AEUserAccountType {
    const ENCODING: Encoding = NSInteger::ENCODING;
}

unsafe impl RefEncode for AEUserAccountType {
    const ENCODING_REF: Encoding = Encoding::Pointer(&Self::ENCODING);
}

/// The set of autocorrect features that you can enable during an assessment.
///
/// Use one or more of the autocorrect modes to set the ``AEAssessmentConfiguration/autocorrectMode-swift.property`` property of an ``AEAssessmentConfiguration`` instance. For example, you can enable both spelling and punctuation corrections by combining ``AEAssessmentConfiguration/AutocorrectMode-swift.struct/spelling`` and ``AEAssessmentConfiguration/AutocorrectMode-swift.struct/punctuation``:
///
/// ```swift
/// let config = AEAssessmentConfiguration()
///
/// #if os(iOS) // Available only on iOS and iPadOS.
/// config.autocorrectMode = [.punctuation, .spelling]
/// #endif
///
/// let session = AEAssessmentSession(configuration: config)
/// ```
///
/// ## Topics
///
/// ### Creating a mode
///
/// - ``AEAssessmentConfiguration/AutocorrectMode-swift.struct/init(rawValue:)``
///
/// ### Modes
///
/// - ``AEAssessmentConfiguration/AutocorrectMode-swift.struct/punctuation``
/// - ``AEAssessmentConfiguration/AutocorrectMode-swift.struct/spelling``
/// - ``AEAutocorrectMode/AEAutocorrectModeNone``
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/automaticassessmentconfiguration/aeautocorrectmode?language=objc)
// NS_OPTIONS
#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, Default)]
pub struct AEAutocorrectMode(pub NSUInteger);
bitflags::bitflags! {
    impl AEAutocorrectMode: NSUInteger {
        #[doc(alias = "AEAutocorrectModeNone")]
        const None = 0;
/// A mode in which autocorrect checks for spelling as the user types.
        #[doc(alias = "AEAutocorrectModeSpelling")]
        const Spelling = 1<<0;
/// A mode in which autocorrect checks punctuation as the user types.
        #[doc(alias = "AEAutocorrectModePunctuation")]
        const Punctuation = 1<<1;
        const _ = !0;
    }
}

unsafe impl Encode for AEAutocorrectMode {
    const ENCODING: Encoding = NSUInteger::ENCODING;
}

unsafe impl RefEncode for AEAutocorrectMode {
    const ENCODING_REF: Encoding = Encoding::Pointer(&Self::ENCODING);
}

extern_class!(
    /// Configuration information for an assessment session.
    ///
    /// Create a configuration instance and pass it to the ``AEAssessmentSession/init(configuration:)`` initializer of an ``AEAssessmentSession`` instance to create a new assessment session. Before using the configuration, indicate which exceptions you want to allow for the assessment session's restrictions by setting values on the configuration instance. For example, you can set values to allow dictation and certain aspects of autocorrect:
    ///
    /// ```swift
    /// let config = AEAssessmentConfiguration()
    ///
    /// #if os(iOS) // These exceptions available only on iOS and iPadOS.
    /// config.allowsDictation = true
    /// config.autocorrectMode = [.punctuation, .spelling]
    /// #endif
    ///
    /// let session = AEAssessmentSession(configuration: config)
    /// ```
    ///
    /// While you provide a configuration instance when creating a session on iOS, iPadOS, and macOS, specific exceptions apply only to certain platforms. In particular, on macOS, you can selectively make specific apps besides your own available during an assessment — for example, to allow users to access a calculator or a dictionary. All other exceptions apply only to iOS and iPadOS.
    ///
    /// ## Topics
    ///
    /// ### Allowing access to other apps
    ///
    /// - ``setConfiguration(_:for:)``
    /// - ``configurationsByApplication``
    /// - ``remove(_:)``
    /// - ``setConfiguration(_:for:)-(AEAssessmentBinaryExecutableConfiguration,_)``
    /// - ``configurationsByBinaryExecutable``
    /// - ``removeBinaryExecutable(_:)``
    /// - ``mainParticipantConfiguration``
    /// - ``AEAssessmentApplication``
    /// - ``AEAssessmentBinaryExecutable``
    /// - ``AEAssessmentParticipantConfiguration``
    ///
    /// ### Allowing accessibility
    ///
    /// - ``allowsAccessibilityAlternativeInputMethods``
    /// - ``allowsAccessibilityBackgroundSounds``
    /// - ``allowsAccessibilityFullKeyboardAccess``
    /// - ``allowsAccessibilityHoverText``
    /// - ``allowsAccessibilityKeyboard``
    /// - ``allowsAccessibilityLiveCaptions``
    /// - ``allowsAccessibilityLiveSpeech``
    /// - ``allowsAccessibilityReader``
    /// - ``allowsAccessibilitySpeech``
    /// - ``allowsAccessibilitySwitchControl``
    /// - ``allowsAccessibilityTypingFeedback``
    /// - ``allowsAccessibilityVoiceControl``
    /// - ``allowsAccessibilityVoiceOver``
    /// - ``allowsAccessibilityZoom``
    /// - ``allowsAccessibilitySpokenContent``
    /// - ``allowsDictation``
    ///
    /// ### Allowing typing assistance
    ///
    /// - ``allowsContinuousPathKeyboard``
    /// - ``allowsKeyboardShortcuts``
    /// - ``allowsPredictiveKeyboard``
    /// - ``allowsPasswordAutoFill``
    ///
    /// ### Allowing corrections
    ///
    /// - ``allowsSpellCheck``
    /// - ``autocorrectMode-swift.property``
    /// - ``AutocorrectMode-swift.struct``
    ///
    /// ### Allowing handoff
    ///
    /// - ``allowsActivityContinuation``
    ///
    /// ### Allowing content capture
    ///
    /// - ``allowsScreenshots``
    ///
    /// ### Controlling force quit
    ///
    /// - ``allowsForceQuit``
    ///
    /// See also [Apple's documentation](https://developer.apple.com/documentation/automaticassessmentconfiguration/aeassessmentconfiguration?language=objc)
    #[unsafe(super(NSObject))]
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub struct AEAssessmentConfiguration;
);

extern_conformance!(
    unsafe impl NSCopying for AEAssessmentConfiguration {}
);

unsafe impl CopyingHelper for AEAssessmentConfiguration {
    type Result = Self;
}

extern_conformance!(
    unsafe impl NSObjectProtocol for AEAssessmentConfiguration {}
);

impl AEAssessmentConfiguration {
    extern_methods!(
        /// The autocorrect mode that specifies which autocorrect features to allow during an assessment.
        ///
        /// Users can turn on autocorrect in the Settings app (General > Keyboard > Auto-Correction). An assessment session disables this feature by default, but you can allow it by setting ``AEAssessmentConfiguration/autocorrectMode-swift.property`` in the ``AEAssessmentConfiguration`` instance that you use to initialize a session. Set the mode's value to some combination of the the values from the ``AEAssessmentConfiguration/AutocorrectMode-swift.struct`` structure.
        #[unsafe(method(autocorrectMode))]
        #[unsafe(method_family = none)]
        pub unsafe fn autocorrectMode(&self) -> AEAutocorrectMode;

        /// Setter for [`autocorrectMode`][Self::autocorrectMode].
        #[unsafe(method(setAutocorrectMode:))]
        #[unsafe(method_family = none)]
        pub unsafe fn setAutocorrectMode(&self, autocorrect_mode: AEAutocorrectMode);

        /// A Boolean value that indicates whether to allow spell check during an assessment.
        ///
        /// Users can activate the spell checker by turning on the Check Spelling feature in the Settings app (General > Keyboard). An assessment session disables spell checking by default, but you can allow it by setting ``AEAssessmentConfiguration/allowsSpellCheck`` to `true` in the ``AEAssessmentConfiguration`` instance that you use to initialize a session.
        #[unsafe(method(allowsSpellCheck))]
        #[unsafe(method_family = none)]
        pub unsafe fn allowsSpellCheck(&self) -> bool;

        /// Setter for [`allowsSpellCheck`][Self::allowsSpellCheck].
        #[unsafe(method(setAllowsSpellCheck:))]
        #[unsafe(method_family = none)]
        pub unsafe fn setAllowsSpellCheck(&self, allows_spell_check: bool);

        /// A Boolean value that indicates whether to enable the predictive keyboard during an assessment.
        ///
        /// Users can turn on the Predictive Keyboard feature in the Settings app (General > Keyboard). An assessment session disables this feature by default, but you can allow it by setting ``AEAssessmentConfiguration/allowsPredictiveKeyboard`` to `true` in the ``AEAssessmentConfiguration`` instance that you use to initialize a session.
        #[unsafe(method(allowsPredictiveKeyboard))]
        #[unsafe(method_family = none)]
        pub unsafe fn allowsPredictiveKeyboard(&self) -> bool;

        /// Setter for [`allowsPredictiveKeyboard`][Self::allowsPredictiveKeyboard].
        #[unsafe(method(setAllowsPredictiveKeyboard:))]
        #[unsafe(method_family = none)]
        pub unsafe fn setAllowsPredictiveKeyboard(&self, allows_predictive_keyboard: bool);

        /// A Boolean value that indicates whether to allow keyboard shortcuts during an assessment.
        ///
        /// Users can add Keyboard Shortcuts in the Settings app (General > Keyboard > Text Replacement). An assessment session disables the use of keyboard shortcuts by default, but you can allow them by setting ``AEAssessmentConfiguration/allowsKeyboardShortcuts`` to `true` in the ``AEAssessmentConfiguration`` instance that you use to initialize a session.
        #[unsafe(method(allowsKeyboardShortcuts))]
        #[unsafe(method_family = none)]
        pub unsafe fn allowsKeyboardShortcuts(&self) -> bool;

        /// Setter for [`allowsKeyboardShortcuts`][Self::allowsKeyboardShortcuts].
        #[unsafe(method(setAllowsKeyboardShortcuts:))]
        #[unsafe(method_family = none)]
        pub unsafe fn setAllowsKeyboardShortcuts(&self, allows_keyboard_shortcuts: bool);

        /// A Boolean value that indicates whether to allow Handoff during an assessment.
        ///
        /// Handoff lets users start an activity on one device and seamlessly resume the activity on another. Users control whether a device participates in Handoff by turning the feature on or off in the Settings app (General > AirPlay
        /// &
        /// Handoff > Handoff). An assessment disables this feature by default, but you can allow users undergoing an assessment to continue to use Handoff by setting ``AEAssessmentConfiguration/allowsActivityContinuation`` to `true`.
        #[unsafe(method(allowsActivityContinuation))]
        #[unsafe(method_family = none)]
        pub unsafe fn allowsActivityContinuation(&self) -> bool;

        /// Setter for [`allowsActivityContinuation`][Self::allowsActivityContinuation].
        #[unsafe(method(setAllowsActivityContinuation:))]
        #[unsafe(method_family = none)]
        pub unsafe fn setAllowsActivityContinuation(&self, allows_activity_continuation: bool);

        /// A Boolean value that indicates whether to allow the use of dictation during an assessment.
        ///
        /// By turning on Enable Dictation (General > Keyboard in the Settings app on iOS and iPadOS), users can speak into their device and have the words they speak converted to text. An assessment session disables this feature by default, but you can allow it by setting ``AEAssessmentConfiguration/allowsDictation`` to `true` in the ``AEAssessmentConfiguration`` instance that you use to initialize a session.
        #[unsafe(method(allowsDictation))]
        #[unsafe(method_family = none)]
        pub unsafe fn allowsDictation(&self) -> bool;

        /// Setter for [`allowsDictation`][Self::allowsDictation].
        #[unsafe(method(setAllowsDictation:))]
        #[unsafe(method_family = none)]
        pub unsafe fn setAllowsDictation(&self, allows_dictation: bool);

        /// A Boolean value that indicates whether to allow alternative input methods for accessibility features during an assessment.
        ///
        /// When the Accessibility Keyboard or Switch Control is enabled, alternative input methods such as Dwell Control may be available. An assessment session disables these alternative input methods by default, but you can allow them by setting ``AEAssessmentConfiguration/allowsAccessibilityAlternativeInputMethods`` to `YES` in the ``AEAssessmentConfiguration`` instance that you use to initialize a session.
        ///
        /// - Note: This property only takes effect when ``AEAssessmentConfiguration/allowsAccessibilityKeyboard`` or ``AEAssessmentConfiguration/allowsAccessibilitySwitchControl`` is `YES`.
        #[unsafe(method(allowsAccessibilityAlternativeInputMethods))]
        #[unsafe(method_family = none)]
        pub unsafe fn allowsAccessibilityAlternativeInputMethods(&self) -> bool;

        /// Setter for [`allowsAccessibilityAlternativeInputMethods`][Self::allowsAccessibilityAlternativeInputMethods].
        #[unsafe(method(setAllowsAccessibilityAlternativeInputMethods:))]
        #[unsafe(method_family = none)]
        pub unsafe fn setAllowsAccessibilityAlternativeInputMethods(
            &self,
            allows_accessibility_alternative_input_methods: bool,
        );

        /// A Boolean value that indicates whether to allow Background Sounds during an assessment.
        ///
        /// Users can enable Background Sounds in the Settings app (Accessibility > Audio
        /// &
        /// Visual > Background Sounds) to play ambient sounds that can mask unwanted environmental noise. An assessment session disables Background Sounds by default, but you can allow it by setting ``AEAssessmentConfiguration/allowsAccessibilityBackgroundSounds`` to `true` in the ``AEAssessmentConfiguration`` instance that you use to initialize a session.
        #[unsafe(method(allowsAccessibilityBackgroundSounds))]
        #[unsafe(method_family = none)]
        pub unsafe fn allowsAccessibilityBackgroundSounds(&self) -> bool;

        /// Setter for [`allowsAccessibilityBackgroundSounds`][Self::allowsAccessibilityBackgroundSounds].
        #[unsafe(method(setAllowsAccessibilityBackgroundSounds:))]
        #[unsafe(method_family = none)]
        pub unsafe fn setAllowsAccessibilityBackgroundSounds(
            &self,
            allows_accessibility_background_sounds: bool,
        );

        /// A Boolean value that indicates whether to allow Full Keyboard Access during an assessment.
        ///
        /// Users can enable Full Keyboard Access in the Settings app (Accessibility > Keyboard > Full Keyboard Access) to navigate and operate the system using only the keyboard. An assessment session **does not** disable Full Keyboard Access by default, but you can disable it by setting ``AEAssessmentConfiguration/allowsAccessibilityFullKeyboardAccess`` to `NO` in the ``AEAssessmentConfiguration`` instance that you use to initialize a session.
        #[unsafe(method(allowsAccessibilityFullKeyboardAccess))]
        #[unsafe(method_family = none)]
        pub unsafe fn allowsAccessibilityFullKeyboardAccess(&self) -> bool;

        /// Setter for [`allowsAccessibilityFullKeyboardAccess`][Self::allowsAccessibilityFullKeyboardAccess].
        #[unsafe(method(setAllowsAccessibilityFullKeyboardAccess:))]
        #[unsafe(method_family = none)]
        pub unsafe fn setAllowsAccessibilityFullKeyboardAccess(
            &self,
            allows_accessibility_full_keyboard_access: bool,
        );

        /// A Boolean value that indicates whether to allow Hover Text during an assessment.
        ///
        /// Users can enable Hover Text in the Settings app (Accessibility > Zoom > Hover Text) to magnify text under the pointer. An assessment session **does not** disable Hover Text by default, but you can disable it by setting ``AEAssessmentConfiguration/allowsAccessibilityHoverText`` to `NO` in the ``AEAssessmentConfiguration`` instance that you use to initialize a session.
        #[unsafe(method(allowsAccessibilityHoverText))]
        #[unsafe(method_family = none)]
        pub unsafe fn allowsAccessibilityHoverText(&self) -> bool;

        /// Setter for [`allowsAccessibilityHoverText`][Self::allowsAccessibilityHoverText].
        #[unsafe(method(setAllowsAccessibilityHoverText:))]
        #[unsafe(method_family = none)]
        pub unsafe fn setAllowsAccessibilityHoverText(&self, allows_accessibility_hover_text: bool);

        /// A Boolean value that indicates whether to allow the Accessibility Keyboard during an assessment.
        ///
        /// Users can enable the Accessibility Keyboard in the Settings app (Accessibility > Keyboard > Accessibility Keyboard) to access an on-screen keyboard. An assessment session **does not** disable the Accessibility Keyboard by default, but you can disable it by setting ``AEAssessmentConfiguration/allowsAccessibilityKeyboard`` to `NO` in the ``AEAssessmentConfiguration`` instance that you use to initialize a session.
        ///
        /// - Note: To allow the full Accessibility Keyboard with alternative input methods (such as Dwell Control), you must also set ``AEAssessmentConfiguration/allowsAccessibilityAlternativeInputMethods`` to `YES`.
        #[unsafe(method(allowsAccessibilityKeyboard))]
        #[unsafe(method_family = none)]
        pub unsafe fn allowsAccessibilityKeyboard(&self) -> bool;

        /// Setter for [`allowsAccessibilityKeyboard`][Self::allowsAccessibilityKeyboard].
        #[unsafe(method(setAllowsAccessibilityKeyboard:))]
        #[unsafe(method_family = none)]
        pub unsafe fn setAllowsAccessibilityKeyboard(&self, allows_accessibility_keyboard: bool);

        /// A Boolean value that indicates whether to allow Live Captions during an assessment.
        ///
        /// Users can enable Live Captions in the Settings app (Accessibility > Live Captions) to receive real-time transcription of spoken audio as text on screen. An assessment session disables Live Captions by default, but you can allow it by setting ``AEAssessmentConfiguration/allowsAccessibilityLiveCaptions`` to `true` in the ``AEAssessmentConfiguration`` instance that you use to initialize a session.
        #[unsafe(method(allowsAccessibilityLiveCaptions))]
        #[unsafe(method_family = none)]
        pub unsafe fn allowsAccessibilityLiveCaptions(&self) -> bool;

        /// Setter for [`allowsAccessibilityLiveCaptions`][Self::allowsAccessibilityLiveCaptions].
        #[unsafe(method(setAllowsAccessibilityLiveCaptions:))]
        #[unsafe(method_family = none)]
        pub unsafe fn setAllowsAccessibilityLiveCaptions(
            &self,
            allows_accessibility_live_captions: bool,
        );

        /// A Boolean value that indicates whether to allow Live Speech during an assessment.
        ///
        /// Users can enable Live Speech in the Settings app (Accessibility > Speech > Live Speech) to type what they want to say and have it spoken aloud. An assessment session disables Live Speech by default, but you can allow it by setting ``AEAssessmentConfiguration/allowsAccessibilityLiveSpeech`` to `true` in the ``AEAssessmentConfiguration`` instance that you use to initialize a session.
        #[unsafe(method(allowsAccessibilityLiveSpeech))]
        #[unsafe(method_family = none)]
        pub unsafe fn allowsAccessibilityLiveSpeech(&self) -> bool;

        /// Setter for [`allowsAccessibilityLiveSpeech`][Self::allowsAccessibilityLiveSpeech].
        #[unsafe(method(setAllowsAccessibilityLiveSpeech:))]
        #[unsafe(method_family = none)]
        pub unsafe fn setAllowsAccessibilityLiveSpeech(
            &self,
            allows_accessibility_live_speech: bool,
        );

        /// A Boolean value that indicates whether to allow the Accessibility Reader during an assessment.
        ///
        /// Users can enable the Accessibility Reader in the Settings app (Accessibility > Read
        /// &
        /// Speak > Accessibility Reader) to have text content formatted or read aloud. An assessment session disables the Accessibility Reader by default, but you can allow it by setting ``AEAssessmentConfiguration/allowsAccessibilityReader`` to `true` in the ``AEAssessmentConfiguration`` instance that you use to initialize a session.
        #[unsafe(method(allowsAccessibilityReader))]
        #[unsafe(method_family = none)]
        pub unsafe fn allowsAccessibilityReader(&self) -> bool;

        /// Setter for [`allowsAccessibilityReader`][Self::allowsAccessibilityReader].
        #[unsafe(method(setAllowsAccessibilityReader:))]
        #[unsafe(method_family = none)]
        pub unsafe fn setAllowsAccessibilityReader(&self, allows_accessibility_reader: bool);

        /// A Boolean value that indicates whether to allow the speech-related accessibility features during an assessment.
        ///
        /// - Important: This property is deprecated. Use ``AEAssessmentConfiguration/allowsAccessibilitySpokenContent`` instead.
        #[deprecated]
        #[unsafe(method(allowsAccessibilitySpeech))]
        #[unsafe(method_family = none)]
        pub unsafe fn allowsAccessibilitySpeech(&self) -> bool;

        /// Setter for [`allowsAccessibilitySpeech`][Self::allowsAccessibilitySpeech].
        #[deprecated]
        #[unsafe(method(setAllowsAccessibilitySpeech:))]
        #[unsafe(method_family = none)]
        pub unsafe fn setAllowsAccessibilitySpeech(&self, allows_accessibility_speech: bool);

        /// A Boolean value that indicates whether to allow Spoken Content during an assessment.
        ///
        /// Users can enable Spoken Content in the Settings app (Accessibility > Read
        /// &
        /// Speak) to have text read aloud. This includes Speak Selection, Speak Screen, and related features. An assessment session disables Spoken Content by default, but you can allow it by setting ``AEAssessmentConfiguration/allowsAccessibilitySpokenContent`` to `true` in the ``AEAssessmentConfiguration`` instance that you use to initialize a session.
        #[unsafe(method(allowsAccessibilitySpokenContent))]
        #[unsafe(method_family = none)]
        pub unsafe fn allowsAccessibilitySpokenContent(&self) -> bool;

        /// Setter for [`allowsAccessibilitySpokenContent`][Self::allowsAccessibilitySpokenContent].
        #[unsafe(method(setAllowsAccessibilitySpokenContent:))]
        #[unsafe(method_family = none)]
        pub unsafe fn setAllowsAccessibilitySpokenContent(
            &self,
            allows_accessibility_spoken_content: bool,
        );

        /// A Boolean value that indicates whether to allow Switch Control during an assessment.
        ///
        /// Users can enable Switch Control in the Settings app (Accessibility > Switch Control) to control their device using adaptive switches. An assessment session **does not** disable Switch Control by default, but you can disable it by setting ``AEAssessmentConfiguration/allowsAccessibilitySwitchControl`` to `NO` in the ``AEAssessmentConfiguration`` instance that you use to initialize a session.
        ///
        /// - Note: To allow Switch Control with alternative input methods (such as Dwell Control), you must also set ``AEAssessmentConfiguration/allowsAccessibilityAlternativeInputMethods`` to `YES`.
        #[unsafe(method(allowsAccessibilitySwitchControl))]
        #[unsafe(method_family = none)]
        pub unsafe fn allowsAccessibilitySwitchControl(&self) -> bool;

        /// Setter for [`allowsAccessibilitySwitchControl`][Self::allowsAccessibilitySwitchControl].
        #[unsafe(method(setAllowsAccessibilitySwitchControl:))]
        #[unsafe(method_family = none)]
        pub unsafe fn setAllowsAccessibilitySwitchControl(
            &self,
            allows_accessibility_switch_control: bool,
        );

        /// A Boolean value that indicates whether to allow accessibility typing feedback during an assessment.
        ///
        /// Users can enable typing feedback features in the Settings app (Accessibility > Keyboards
        /// &
        /// Typing > Typing Feedback)  to receive audio feedback when typing. An assessment session disables these accessibility typing feedback features by default, but you can allow them by setting ``AEAssessmentConfiguration/allowsAccessibilityTypingFeedback`` to `true` in the ``AEAssessmentConfiguration`` instance that you use to initialize a session.
        #[unsafe(method(allowsAccessibilityTypingFeedback))]
        #[unsafe(method_family = none)]
        pub unsafe fn allowsAccessibilityTypingFeedback(&self) -> bool;

        /// Setter for [`allowsAccessibilityTypingFeedback`][Self::allowsAccessibilityTypingFeedback].
        #[unsafe(method(setAllowsAccessibilityTypingFeedback:))]
        #[unsafe(method_family = none)]
        pub unsafe fn setAllowsAccessibilityTypingFeedback(
            &self,
            allows_accessibility_typing_feedback: bool,
        );

        /// A Boolean value that indicates whether to allow Voice Control during an assessment.
        ///
        /// Users can enable Voice Control in the Settings app (Accessibility > Voice Control) to control their device using voice commands. An assessment session **does not** disable Voice Control by default, but you can disable it by setting ``AEAssessmentConfiguration/allowsAccessibilityVoiceControl`` to `NO` in the ``AEAssessmentConfiguration`` instance that you use to initialize a session.
        #[unsafe(method(allowsAccessibilityVoiceControl))]
        #[unsafe(method_family = none)]
        pub unsafe fn allowsAccessibilityVoiceControl(&self) -> bool;

        /// Setter for [`allowsAccessibilityVoiceControl`][Self::allowsAccessibilityVoiceControl].
        #[unsafe(method(setAllowsAccessibilityVoiceControl:))]
        #[unsafe(method_family = none)]
        pub unsafe fn setAllowsAccessibilityVoiceControl(
            &self,
            allows_accessibility_voice_control: bool,
        );

        /// A Boolean value that indicates whether to allow VoiceOver during an assessment.
        ///
        /// Users can enable VoiceOver in the Settings app (Accessibility > VoiceOver) to receive spoken descriptions of on-screen elements and gestures for navigating the interface. An assessment session **does not** disable VoiceOver by default, but you can disable it by setting ``AEAssessmentConfiguration/allowsAccessibilityVoiceOver`` to `NO` in the ``AEAssessmentConfiguration`` instance that you use to initialize a session.
        #[unsafe(method(allowsAccessibilityVoiceOver))]
        #[unsafe(method_family = none)]
        pub unsafe fn allowsAccessibilityVoiceOver(&self) -> bool;

        /// Setter for [`allowsAccessibilityVoiceOver`][Self::allowsAccessibilityVoiceOver].
        #[unsafe(method(setAllowsAccessibilityVoiceOver:))]
        #[unsafe(method_family = none)]
        pub unsafe fn setAllowsAccessibilityVoiceOver(&self, allows_accessibility_voice_over: bool);

        /// A Boolean value that indicates whether to allow Zoom during an assessment.
        ///
        /// Users can enable Zoom in the Settings app (Accessibility > Zoom) to magnify the screen. An assessment session **does not** disable Zoom by default, but you can disable it by setting ``AEAssessmentConfiguration/allowsAccessibilityZoom`` to `NO` in the ``AEAssessmentConfiguration`` instance that you use to initialize a session.
        #[unsafe(method(allowsAccessibilityZoom))]
        #[unsafe(method_family = none)]
        pub unsafe fn allowsAccessibilityZoom(&self) -> bool;

        /// Setter for [`allowsAccessibilityZoom`][Self::allowsAccessibilityZoom].
        #[unsafe(method(setAllowsAccessibilityZoom:))]
        #[unsafe(method_family = none)]
        pub unsafe fn setAllowsAccessibilityZoom(&self, allows_accessibility_zoom: bool);

        /// A Boolean value that indicates whether to allow password autofill during an assessment.
        ///
        /// Users can store passwords for use with Password Autofill by turning on the feature in the Settings app (General > Passwords > AutoFill Passwords). An assessment session disables Password Autofill by default, but you can allow it by setting ``AEAssessmentConfiguration/allowsPasswordAutoFill`` to `true` in the ``AEAssessmentConfiguration`` instance that you use to initialize a session.
        #[unsafe(method(allowsPasswordAutoFill))]
        #[unsafe(method_family = none)]
        pub unsafe fn allowsPasswordAutoFill(&self) -> bool;

        /// Setter for [`allowsPasswordAutoFill`][Self::allowsPasswordAutoFill].
        #[unsafe(method(setAllowsPasswordAutoFill:))]
        #[unsafe(method_family = none)]
        pub unsafe fn setAllowsPasswordAutoFill(&self, allows_password_auto_fill: bool);

        /// A Boolean value that indicates whether to allow Slide to Type to operate during an assessment.
        ///
        /// Users can turn on Slide to Type in the Settings app (General > Keyboard). An assessment session disables this feature by default, but you can allow it by setting ``AEAssessmentConfiguration/allowsContinuousPathKeyboard`` to `true` in the ``AEAssessmentConfiguration`` instance that you use to initialize a session.
        #[unsafe(method(allowsContinuousPathKeyboard))]
        #[unsafe(method_family = none)]
        pub unsafe fn allowsContinuousPathKeyboard(&self) -> bool;

        /// Setter for [`allowsContinuousPathKeyboard`][Self::allowsContinuousPathKeyboard].
        #[unsafe(method(setAllowsContinuousPathKeyboard:))]
        #[unsafe(method_family = none)]
        pub unsafe fn setAllowsContinuousPathKeyboard(&self, allows_continuous_path_keyboard: bool);

        /// A Boolean value that indicates whether to allow screenshots copied to the clipboard during an assessment.
        ///
        /// An assessment session disables the ability to take screenshots by default to maintain assessment integrity. This property specifically applies to screenshots that are copied to the clipboard, typically those taken using the Command+Control+Shift+3 and Command+Control+Shift+4 keyboard shortcuts. You can allow clipboard screenshots by setting `allowsScreenshots` to `true`.
        ///
        /// - Note: The clipboard is cleared before the assessment session ends to prevent exporting captured content.
        #[unsafe(method(allowsScreenshots))]
        #[unsafe(method_family = none)]
        pub unsafe fn allowsScreenshots(&self) -> bool;

        /// Setter for [`allowsScreenshots`][Self::allowsScreenshots].
        #[unsafe(method(setAllowsScreenshots:))]
        #[unsafe(method_family = none)]
        pub unsafe fn setAllowsScreenshots(&self, allows_screenshots: bool);

        /// A Boolean value that indicates whether to allow the emoji keyboard during an assessment.
        ///
        /// Users can access the emoji keyboard by tapping the emoji button on the keyboard (iOS) or through the Edit menu and keyboard shortcuts (macOS). An assessment session disables access to the emoji keyboard by default, but you can allow it by setting ``AEAssessmentConfiguration/allowsEmojiKeyboard`` to `true` in the ``AEAssessmentConfiguration`` instance that you use to initialize a session.
        #[unsafe(method(allowsEmojiKeyboard))]
        #[unsafe(method_family = none)]
        pub unsafe fn allowsEmojiKeyboard(&self) -> bool;

        /// Setter for [`allowsEmojiKeyboard`][Self::allowsEmojiKeyboard].
        #[unsafe(method(setAllowsEmojiKeyboard:))]
        #[unsafe(method_family = none)]
        pub unsafe fn setAllowsEmojiKeyboard(&self, allows_emoji_keyboard: bool);
    );

    extern_methods!(
        /// A Boolean value that indicates whether to allow user script execution during an assessment.
        ///
        /// User scripts, such as AppleScripts or Automator workflows, can automate tasks on the system. An assessment session disables user script execution by default, but you can allow it by setting ``AEAssessmentConfiguration/allowsUserScriptExecution`` to `true` in the ``AEAssessmentConfiguration`` instance that you use to initialize a session.
        #[unsafe(method(allowsUserScriptExecution))]
        #[unsafe(method_family = none)]
        pub unsafe fn allowsUserScriptExecution(&self) -> bool;

        /// Setter for [`allowsUserScriptExecution`][Self::allowsUserScriptExecution].
        #[unsafe(method(setAllowsUserScriptExecution:))]
        #[unsafe(method_family = none)]
        pub unsafe fn setAllowsUserScriptExecution(&self, allows_user_script_execution: bool);

        /// A Boolean value that indicates whether to allow autofill during an assessment.
        ///
        /// Users can enable autofill in System Settings (Passwords > Password Options > AutoFill Passwords and Passkeys). An assessment session disables autofill by default, but you can allow it by setting ``AEAssessmentConfiguration/allowsAutoFill`` to `true` in the ``AEAssessmentConfiguration`` instance that you use to initialize a session.
        #[unsafe(method(allowsAutoFill))]
        #[unsafe(method_family = none)]
        pub unsafe fn allowsAutoFill(&self) -> bool;

        /// Setter for [`allowsAutoFill`][Self::allowsAutoFill].
        #[unsafe(method(setAllowsAutoFill:))]
        #[unsafe(method_family = none)]
        pub unsafe fn setAllowsAutoFill(&self, allows_auto_fill: bool);

        /// A Boolean value that indicates whether to allow Chinese and Japanese structural input during an assessment.
        ///
        /// Chinese and Japanese structural input methods allow users to enter characters using component-based input. An assessment session disables structural input by default, but you can allow it by setting ``AEAssessmentConfiguration/allowsStructuralInput`` to `true` in the ``AEAssessmentConfiguration`` instance that you use to initialize a session.
        #[unsafe(method(allowsStructuralInput))]
        #[unsafe(method_family = none)]
        pub unsafe fn allowsStructuralInput(&self) -> bool;

        /// Setter for [`allowsStructuralInput`][Self::allowsStructuralInput].
        #[unsafe(method(setAllowsStructuralInput:))]
        #[unsafe(method_family = none)]
        pub unsafe fn setAllowsStructuralInput(&self, allows_structural_input: bool);

        /// A Boolean value that indicates whether to allow force quitting apps during an assessment.
        ///
        /// Users can force quit apps by pressing Shift-Option-Command-Escape to force quit the frontmost app. An assessment session disables force quit by default, but you can allow it by setting ``AEAssessmentConfiguration/allowsForceQuit`` to `true` in the ``AEAssessmentConfiguration`` instance that you use to initialize a session.
        ///
        /// - Note: This property controls only the force quit keyboard shortcuts. Setting it to `false` does not remove the Force Quit item from the Apple menu. Use ``AEAssessmentConfiguration/allowedAppleMenuItems`` to configure the allowed Apple menu items.
        #[unsafe(method(allowsForceQuit))]
        #[unsafe(method_family = none)]
        pub unsafe fn allowsForceQuit(&self) -> bool;

        /// Setter for [`allowsForceQuit`][Self::allowsForceQuit].
        #[unsafe(method(setAllowsForceQuit:))]
        #[unsafe(method_family = none)]
        pub unsafe fn setAllowsForceQuit(&self, allows_force_quit: bool);

        /// The set of allowed directories and files that participants can access during an assessment.
        ///
        /// By default, participants have restricted file system access. Use this property to specify file URLs to directories and files that should be accessible during the assessment session.
        ///
        /// The default value is `nil`, which preserves the default unrestricted access behavior.
        #[unsafe(method(allowedDirectoriesAndFiles))]
        #[unsafe(method_family = none)]
        pub unsafe fn allowedDirectoriesAndFiles(&self) -> Option<Retained<NSSet<NSURL>>>;

        /// Setter for [`allowedDirectoriesAndFiles`][Self::allowedDirectoriesAndFiles].
        ///
        /// This is [copied][objc2_foundation::NSCopying::copy] when set.
        #[unsafe(method(setAllowedDirectoriesAndFiles:))]
        #[unsafe(method_family = none)]
        pub unsafe fn setAllowedDirectoriesAndFiles(
            &self,
            allowed_directories_and_files: Option<&NSSet<NSURL>>,
        );

        /// A Boolean value that indicates whether to allow the Dock during an assessment.
        ///
        /// An assessment session hides the Dock by default, but you can allow it by setting ``AEAssessmentConfiguration/allowsDock`` to `true` in the ``AEAssessmentConfiguration`` instance that you use to initialize a session.
        #[unsafe(method(allowsDock))]
        #[unsafe(method_family = none)]
        pub unsafe fn allowsDock(&self) -> bool;

        /// Setter for [`allowsDock`][Self::allowsDock].
        #[unsafe(method(setAllowsDock:))]
        #[unsafe(method_family = none)]
        pub unsafe fn setAllowsDock(&self, allows_dock: bool);

        /// A Boolean value that indicates whether to allow the menu bar during an assessment.
        ///
        /// An assessment session hides the menu bar by default, but you can allow it by setting ``AEAssessmentConfiguration/allowsMenuBar`` to `true` in the ``AEAssessmentConfiguration`` instance that you use to initialize a session.
        #[unsafe(method(allowsMenuBar))]
        #[unsafe(method_family = none)]
        pub unsafe fn allowsMenuBar(&self) -> bool;

        /// Setter for [`allowsMenuBar`][Self::allowsMenuBar].
        #[unsafe(method(setAllowsMenuBar:))]
        #[unsafe(method_family = none)]
        pub unsafe fn setAllowsMenuBar(&self, allows_menu_bar: bool);

        /// The set of allowed Apple menu items during an assessment.
        ///
        /// By default, all Apple menu items are restricted during an assessment. Use this property
        /// to specify which menu items should be accessible.
        ///
        /// - Note: ``AEAppleMenuItemAboutThisMac`` is always visible during assessment sessions regardless of configuration.
        #[unsafe(method(allowedAppleMenuItems))]
        #[unsafe(method_family = none)]
        pub unsafe fn allowedAppleMenuItems(&self) -> Option<Retained<NSSet<AEAppleMenuItem>>>;

        /// Setter for [`allowedAppleMenuItems`][Self::allowedAppleMenuItems].
        ///
        /// This is [copied][objc2_foundation::NSCopying::copy] when set.
        #[unsafe(method(setAllowedAppleMenuItems:))]
        #[unsafe(method_family = none)]
        pub unsafe fn setAllowedAppleMenuItems(
            &self,
            allowed_apple_menu_items: Option<&NSSet<AEAppleMenuItem>>,
        );

        /// The set of menu bar items that should remain visible during an assessment.
        ///
        /// When `allowsMenuBar` is `true`, the menu bar is restricted to only the items
        /// specified in this set. If this property is `nil`, all menu bar items are allowed
        /// (unrestricted menu bar).
        ///
        /// - Note: This property only takes effect when `allowsMenuBar` is `true`.
        #[unsafe(method(allowedMenuBarItems))]
        #[unsafe(method_family = none)]
        pub unsafe fn allowedMenuBarItems(&self) -> Option<Retained<NSSet<AEMenuBarItem>>>;

        /// Setter for [`allowedMenuBarItems`][Self::allowedMenuBarItems].
        ///
        /// This is [copied][objc2_foundation::NSCopying::copy] when set.
        #[unsafe(method(setAllowedMenuBarItems:))]
        #[unsafe(method_family = none)]
        pub unsafe fn setAllowedMenuBarItems(
            &self,
            allowed_menu_bar_items: Option<&NSSet<AEMenuBarItem>>,
        );

        /// A Boolean value that indicates whether only participant applications are allowed to run during an assessment.
        #[unsafe(method(allowOnlyParticipantsToRun))]
        #[unsafe(method_family = none)]
        pub unsafe fn allowOnlyParticipantsToRun(&self) -> bool;

        /// Setter for [`allowOnlyParticipantsToRun`][Self::allowOnlyParticipantsToRun].
        #[unsafe(method(setAllowOnlyParticipantsToRun:))]
        #[unsafe(method_family = none)]
        pub unsafe fn setAllowOnlyParticipantsToRun(&self, allow_only_participants_to_run: bool);

        /// A Boolean value that indicates whether the assessment allows Lockdown Mode to be active.
        ///
        /// When set to `false`, the assessment session will only start if Lockdown Mode is not enabled on the device. This requirement is not enforced by default.
        #[unsafe(method(allowLockdownMode))]
        #[unsafe(method_family = none)]
        pub unsafe fn allowLockdownMode(&self) -> bool;

        /// Setter for [`allowLockdownMode`][Self::allowLockdownMode].
        #[unsafe(method(setAllowLockdownMode:))]
        #[unsafe(method_family = none)]
        pub unsafe fn setAllowLockdownMode(&self, allow_lockdown_mode: bool);

        /// A Boolean value that indicates whether the assessment allows iCloud Private Relay to be active.
        ///
        /// When set to `false`, the assessment session will only start if iCloud Private Relay is not enabled. This requirement is not enforced by default.
        #[unsafe(method(allowPrivateRelay))]
        #[unsafe(method_family = none)]
        pub unsafe fn allowPrivateRelay(&self) -> bool;

        /// Setter for [`allowPrivateRelay`][Self::allowPrivateRelay].
        #[unsafe(method(setAllowPrivateRelay:))]
        #[unsafe(method_family = none)]
        pub unsafe fn setAllowPrivateRelay(&self, allow_private_relay: bool);

        /// A Boolean value that indicates whether the assessment allows running inside a virtual machine.
        ///
        /// When set to `false`, the assessment session will only start if the device is not a virtual machine. This requirement is not enforced by default; virtual machines are allowed unless you opt out.
        ///
        /// > Important: This check is advisory, not a security guarantee. Setting `allowVirtualMachine` to `false` may not block an assessment session in every virtualized environment. Use this property to steer proctored exams toward physical hardware; it doesn't provide a cryptographic attestation that the session is running on a physical machine.
        ///
        /// For stronger assurances about the runtime environment, pair this property with
        /// [App Attest](https://developer.apple.com/documentation/DeviceCheck) on macOS.
        #[unsafe(method(allowVirtualMachine))]
        #[unsafe(method_family = none)]
        pub unsafe fn allowVirtualMachine(&self) -> bool;

        /// Setter for [`allowVirtualMachine`][Self::allowVirtualMachine].
        #[unsafe(method(setAllowVirtualMachine:))]
        #[unsafe(method_family = none)]
        pub unsafe fn setAllowVirtualMachine(&self, allow_virtual_machine: bool);

        /// A Boolean value that indicates whether the device must be managed to start an assessment.
        ///
        /// When set to `true`, the assessment session will only start if the device is enrolled in a Mobile Device Management (MDM) solution. This requirement is disabled by default.
        #[unsafe(method(requiresManagedDevice))]
        #[unsafe(method_family = none)]
        pub unsafe fn requiresManagedDevice(&self) -> bool;

        /// Setter for [`requiresManagedDevice`][Self::requiresManagedDevice].
        #[unsafe(method(setRequiresManagedDevice:))]
        #[unsafe(method_family = none)]
        pub unsafe fn setRequiresManagedDevice(&self, requires_managed_device: bool);

        /// A Boolean value that indicates whether System Integrity Protection (SIP) must be enabled to start an assessment.
        ///
        /// When set to `true`, the assessment session will only start if System Integrity Protection is enabled on the device. This requirement is disabled by default.
        ///
        /// > Important: This check is advisory, not a security guarantee. The framework can't reliably detect whether SIP is enabled on systems where the user has administrator privileges, so setting `requiresSIP` to `true` may not block an assessment session when SIP is in fact disabled. Use this property to prompt users to re-enable SIP if they turned it off for unrelated reasons; it doesn't indicate whether the system was modified while SIP was previously disabled.
        ///
        /// For stronger assurances that SIP is enabled, pair this property with [App Attest](https://developer.apple.com/documentation/DeviceCheck) on macOS.
        #[unsafe(method(requiresSIP))]
        #[unsafe(method_family = none)]
        pub unsafe fn requiresSIP(&self) -> bool;

        /// Setter for [`requiresSIP`][Self::requiresSIP].
        #[unsafe(method(setRequiresSIP:))]
        #[unsafe(method_family = none)]
        pub unsafe fn setRequiresSIP(&self, requires_sip: bool);

        /// A Boolean value that indicates whether only a single user account must be logged in to start an assessment.
        ///
        /// When set to `true`, the assessment session will only start if there is exactly one user account logged in on the device. This requirement is disabled by default.
        #[unsafe(method(requiresSingleUser))]
        #[unsafe(method_family = none)]
        pub unsafe fn requiresSingleUser(&self) -> bool;

        /// Setter for [`requiresSingleUser`][Self::requiresSingleUser].
        #[unsafe(method(setRequiresSingleUser:))]
        #[unsafe(method_family = none)]
        pub unsafe fn setRequiresSingleUser(&self, requires_single_user: bool);

        /// Specifies the type of user account required to start an assessment.
        ///
        /// This property defines the account requirement for starting an assessment session. Set it to `.standard` to require a non-administrator account, `.guest` to require a guest account, or `.any` (the default) to allow any account type.
        #[unsafe(method(requiresUserAccountType))]
        #[unsafe(method_family = none)]
        pub unsafe fn requiresUserAccountType(&self) -> AEUserAccountType;

        /// Setter for [`requiresUserAccountType`][Self::requiresUserAccountType].
        #[unsafe(method(setRequiresUserAccountType:))]
        #[unsafe(method_family = none)]
        pub unsafe fn setRequiresUserAccountType(
            &self,
            requires_user_account_type: AEUserAccountType,
        );

        /// The app-specific configuration for the app that invokes the assessment.
        ///
        /// Use this property to get and customize the app-specific configuration that's applied to your own app. For example, you can set the `allowsNetworkAccess` property for your own app:
        ///
        /// ```swift
        /// let config = AEAssessmentConfiguration()
        /// config.mainParticipantConfiguration.allowsNetworkAccess = false
        /// ```
        #[unsafe(method(mainParticipantConfiguration))]
        #[unsafe(method_family = none)]
        pub unsafe fn mainParticipantConfiguration(
            &self,
        ) -> Retained<AEAssessmentParticipantConfiguration>;

        /// The collection of apps available during an assessment, along with their associated configurations.
        ///
        /// Access this property to get a list of the currently allowed secondary apps and their individual configurations. Add apps to the list by calling the ``AEAssessmentConfiguration/setConfiguration(_:for:)`` method. Remove them from the list by calling the ``AEAssessmentConfiguration/remove(_:)`` method.
        #[unsafe(method(configurationsByApplication))]
        #[unsafe(method_family = none)]
        pub unsafe fn configurationsByApplication(
            &self,
        ) -> Retained<NSDictionary<AEAssessmentApplication, AEAssessmentParticipantConfiguration>>;

        /// Adds an app to the list of apps available during an assessment.
        ///
        /// Use this method to make an app besides your own available during an assessment. Create a representation of the app that you want to allow as an ``AEAssessmentApplication`` instance, and the configuration for that app using an ``AEAssessmentParticipantConfiguration`` instance:
        ///
        /// ```swift
        /// let calculator = AEAssessmentApplication(bundleIdentifier: "com.apple.calculator")
        /// let calculatorConfig = AEAssessmentParticipantConfiguration()
        /// calculatorConfig.allowsNetworkAccess = false // Calculator doesn't need the network.
        /// ```
        ///
        /// Use the app and its configuration to create an assessment configuration, and either create an assessment session with that, or update an existing session as shown below:
        ///
        /// ```swift
        /// let configuration = AEAssessmentConfiguration()
        /// configuration.setConfiguration(calculatorConfig, for: calculator)
        /// session.update(to: configuration)
        /// ```
        ///
        /// You can get a list of the currently allowed apps by accessing the ``AEAssessmentConfiguration/configurationsByApplication`` property. You can disallow a previously allowed app by using the ``AEAssessmentConfiguration/remove(_:)`` method.
        ///
        /// - Parameters:
        /// - configuration: The configuration of the secondary app.
        /// - application: The app that you want to configure.
        #[unsafe(method(setConfiguration:forApplication:))]
        #[unsafe(method_family = none)]
        pub unsafe fn setConfiguration_forApplication(
            &self,
            configuration: &AEAssessmentParticipantConfiguration,
            application: &AEAssessmentApplication,
        );

        /// Removes the availability of a previously allowed app.
        ///
        /// Use this method to remove apps that you previously added to the list of apps that are available during an assessment with the ``AEAssessmentConfiguration/setConfiguration(_:for:)`` method. You can get the list of currently allowed apps by accessing the configuration's ``AEAssessmentConfiguration/configurationsByApplication`` property.
        ///
        /// - Parameters:
        /// - application: The app that you want to remove from the list of allowed secondary apps.
        #[unsafe(method(removeApplication:))]
        #[unsafe(method_family = none)]
        pub unsafe fn removeApplication(&self, application: &AEAssessmentApplication);

        /// The collection of executable participants available during an assessment, along with their associated configurations.
        ///
        /// Add executables with ``AEAssessmentConfiguration/setConfiguration(_:for:)-(AEAssessmentBinaryExecutableConfiguration,_)`` and remove them with ``AEAssessmentConfiguration/removeBinaryExecutable(_:)``.
        ///
        /// - SeeAlso: ``AEAssessmentBinaryExecutable``
        #[unsafe(method(configurationsByBinaryExecutable))]
        #[unsafe(method_family = none)]
        pub unsafe fn configurationsByBinaryExecutable(
            &self,
        ) -> Retained<
            NSDictionary<AEAssessmentBinaryExecutable, AEAssessmentBinaryExecutableConfiguration>,
        >;

        /// Adds an executable participant to the list of participants available during an assessment.
        ///
        /// - Parameters:
        /// - configuration: The configuration of the executable participant.
        /// - binaryExecutable: The executable that you want to configure.
        ///
        /// - SeeAlso: ``AEAssessmentBinaryExecutable``
        #[unsafe(method(setConfiguration:forBinaryExecutable:))]
        #[unsafe(method_family = none)]
        pub unsafe fn setConfiguration_forBinaryExecutable(
            &self,
            configuration: &AEAssessmentBinaryExecutableConfiguration,
            binary_executable: &AEAssessmentBinaryExecutable,
        );

        /// Removes the availability of a previously added executable participant.
        ///
        /// - Parameters:
        /// - binaryExecutable: The executable that you want to remove from the list of allowed participants.
        #[unsafe(method(removeBinaryExecutable:))]
        #[unsafe(method_family = none)]
        pub unsafe fn removeBinaryExecutable(
            &self,
            binary_executable: &AEAssessmentBinaryExecutable,
        );
    );
}

/// Methods declared on superclass `NSObject`.
impl AEAssessmentConfiguration {
    extern_methods!(
        #[unsafe(method(init))]
        #[unsafe(method_family = init)]
        pub unsafe fn init(this: Allocated<Self>) -> Retained<Self>;

        #[unsafe(method(new))]
        #[unsafe(method_family = new)]
        pub unsafe fn new() -> Retained<Self>;
    );
}

extern_class!(
    /// [Apple's documentation](https://developer.apple.com/documentation/automaticassessmentconfiguration/aeassessmentparticipantconfiguration?language=objc)
    #[unsafe(super(NSObject))]
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub struct AEAssessmentParticipantConfiguration;
);

extern_conformance!(
    unsafe impl NSCopying for AEAssessmentParticipantConfiguration {}
);

unsafe impl CopyingHelper for AEAssessmentParticipantConfiguration {
    type Result = Self;
}

extern_conformance!(
    unsafe impl NSObjectProtocol for AEAssessmentParticipantConfiguration {}
);

impl AEAssessmentParticipantConfiguration {
    extern_methods!(
        /// Returns the set of allowed menu item titles for the given language
        /// identifier, or
        /// `nil`if no items have been configured for that
        /// identifier.
        ///
        /// Menu item titles are matched against the participant application's
        /// localized menu items at the time the assessment session begins.
        /// The system resolves each language identifier to the best-matching
        /// localization the application bundle provides, so an exact locale
        /// match is not required.
        ///
        ///
        /// Parameter `languageIdentifier`: A BCP 47 language identifier
        /// (for example,
        /// `en`or
        /// `zh-Hans`).
        #[unsafe(method(allowedMenuItemsForLanguageIdentifier:))]
        #[unsafe(method_family = none)]
        pub unsafe fn allowedMenuItemsForLanguageIdentifier(
            &self,
            language_identifier: &NSString,
        ) -> Option<Retained<NSSet<NSString>>>;

        /// Sets the allowed menu item titles for the given language identifier.
        ///
        /// Titles must match the participant application's localized menu item
        /// strings for the corresponding language.
        ///
        /// If multiple language identifiers resolve to the same application
        /// localization, the system combines their sets of allowed menu items.
        ///
        ///
        /// Parameter `menuItems`: The set of menu item titles to allow, or
        /// `nil`to
        /// remove the entry for
        /// `languageIdentifier.`
        /// Parameter `languageIdentifier`: A BCP 47 language identifier
        /// (for example,
        /// `en`or
        /// `zh-Hans`).
        #[unsafe(method(setAllowedMenuItems:forLanguageIdentifier:))]
        #[unsafe(method_family = none)]
        pub unsafe fn setAllowedMenuItems_forLanguageIdentifier(
            &self,
            menu_items: Option<&NSSet<NSString>>,
            language_identifier: &NSString,
        );

        /// The set of language identifiers for which allowed menu items have
        /// been configured.
        ///
        /// Contains only identifiers explicitly added via
        /// `setAllowedMenuItems:forLanguageIdentifier:`. Does not include
        /// identifiers inferred through localization resolution.
        #[unsafe(method(allowedMenuItemLanguageIdentifiers))]
        #[unsafe(method_family = none)]
        pub unsafe fn allowedMenuItemLanguageIdentifiers(&self) -> Retained<NSSet<NSString>>;

        #[unsafe(method(allowsNetworkAccess))]
        #[unsafe(method_family = none)]
        pub unsafe fn allowsNetworkAccess(&self) -> bool;

        /// Setter for [`allowsNetworkAccess`][Self::allowsNetworkAccess].
        #[unsafe(method(setAllowsNetworkAccess:))]
        #[unsafe(method_family = none)]
        pub unsafe fn setAllowsNetworkAccess(&self, allows_network_access: bool);

        #[unsafe(method(isRequired))]
        #[unsafe(method_family = none)]
        pub unsafe fn isRequired(&self) -> bool;

        /// Setter for [`isRequired`][Self::isRequired].
        #[unsafe(method(setRequired:))]
        #[unsafe(method_family = none)]
        pub unsafe fn setRequired(&self, required: bool);

        #[unsafe(method(configurationInfo))]
        #[unsafe(method_family = none)]
        pub unsafe fn configurationInfo(&self) -> Retained<NSDictionary<NSString, AnyObject>>;

        /// Setter for [`configurationInfo`][Self::configurationInfo].
        ///
        /// This is [copied][objc2_foundation::NSCopying::copy] when set.
        ///
        /// # Safety
        ///
        /// `configuration_info` generic should be of the correct type.
        #[unsafe(method(setConfigurationInfo:))]
        #[unsafe(method_family = none)]
        pub unsafe fn setConfigurationInfo(
            &self,
            configuration_info: &NSDictionary<NSString, AnyObject>,
        );

        #[unsafe(method(init))]
        #[unsafe(method_family = init)]
        pub unsafe fn init(this: Allocated<Self>) -> Retained<Self>;

        #[unsafe(method(new))]
        #[unsafe(method_family = new)]
        pub unsafe fn new() -> Retained<Self>;
    );
}

extern_class!(
    /// [Apple's documentation](https://developer.apple.com/documentation/automaticassessmentconfiguration/aeassessmentsession?language=objc)
    #[unsafe(super(NSObject))]
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub struct AEAssessmentSession;
);

extern_conformance!(
    unsafe impl NSObjectProtocol for AEAssessmentSession {}
);

impl AEAssessmentSession {
    extern_methods!(
        #[unsafe(method(supportsMultipleParticipants))]
        #[unsafe(method_family = none)]
        pub unsafe fn supportsMultipleParticipants() -> bool;

        #[unsafe(method(supportsConfigurationUpdates))]
        #[unsafe(method_family = none)]
        pub unsafe fn supportsConfigurationUpdates() -> bool;

        #[unsafe(method(delegate))]
        #[unsafe(method_family = none)]
        pub unsafe fn delegate(
            &self,
        ) -> Option<Retained<ProtocolObject<dyn AEAssessmentSessionDelegate>>>;

        /// Setter for [`delegate`][Self::delegate].
        ///
        /// This is a [weak property][objc2::topics::weak_property].
        #[unsafe(method(setDelegate:))]
        #[unsafe(method_family = none)]
        pub unsafe fn setDelegate(
            &self,
            delegate: Option<&ProtocolObject<dyn AEAssessmentSessionDelegate>>,
        );

        #[unsafe(method(configuration))]
        #[unsafe(method_family = none)]
        pub unsafe fn configuration(&self) -> Retained<AEAssessmentConfiguration>;

        #[unsafe(method(isActive))]
        #[unsafe(method_family = none)]
        pub unsafe fn isActive(&self) -> bool;

        #[unsafe(method(initWithConfiguration:))]
        #[unsafe(method_family = init)]
        pub unsafe fn initWithConfiguration(
            this: Allocated<Self>,
            configuration: &AEAssessmentConfiguration,
        ) -> Retained<Self>;

        // -init (unavailable)

        // +new (unavailable)

        #[unsafe(method(begin))]
        #[unsafe(method_family = none)]
        pub unsafe fn begin(&self);

        #[unsafe(method(end))]
        #[unsafe(method_family = none)]
        pub unsafe fn end(&self);

        #[unsafe(method(updateToConfiguration:))]
        #[unsafe(method_family = none)]
        pub unsafe fn updateToConfiguration(&self, configuration: &AEAssessmentConfiguration);
    );
}

extern_protocol!(
    /// [Apple's documentation](https://developer.apple.com/documentation/automaticassessmentconfiguration/aeassessmentsessiondelegate?language=objc)
    pub unsafe trait AEAssessmentSessionDelegate: NSObjectProtocol {
        #[optional]
        #[unsafe(method(assessmentSessionDidBegin:))]
        #[unsafe(method_family = none)]
        unsafe fn assessmentSessionDidBegin(&self, session: &AEAssessmentSession);

        #[optional]
        #[unsafe(method(assessmentSession:failedToBeginWithError:))]
        #[unsafe(method_family = none)]
        unsafe fn assessmentSession_failedToBeginWithError(
            &self,
            session: &AEAssessmentSession,
            error: &NSError,
        );

        #[optional]
        #[unsafe(method(assessmentSession:wasInterruptedWithError:))]
        #[unsafe(method_family = none)]
        unsafe fn assessmentSession_wasInterruptedWithError(
            &self,
            session: &AEAssessmentSession,
            error: &NSError,
        );

        #[optional]
        #[unsafe(method(assessmentSessionDidEnd:))]
        #[unsafe(method_family = none)]
        unsafe fn assessmentSessionDidEnd(&self, session: &AEAssessmentSession);

        #[optional]
        #[unsafe(method(assessmentSessionDidUpdate:))]
        #[unsafe(method_family = none)]
        unsafe fn assessmentSessionDidUpdate(&self, session: &AEAssessmentSession);

        #[optional]
        #[unsafe(method(assessmentSession:failedToUpdateToConfiguration:error:))]
        #[unsafe(method_family = none)]
        unsafe fn assessmentSession_failedToUpdateToConfiguration_error(
            &self,
            session: &AEAssessmentSession,
            configuration: &AEAssessmentConfiguration,
            error: &NSError,
        );
    }
);

extern "C" {
    /// [Apple's documentation](https://developer.apple.com/documentation/automaticassessmentconfiguration/aeassessmenterrordomain?language=objc)
    pub static AEAssessmentErrorDomain: &'static NSErrorDomain;
}

/// [Apple's documentation](https://developer.apple.com/documentation/automaticassessmentconfiguration/aeassessmenterrorcode?language=objc)
// NS_ERROR_ENUM
#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct AEAssessmentErrorCode(pub NSInteger);
impl AEAssessmentErrorCode {
    #[doc(alias = "AEAssessmentErrorUnknown")]
    pub const Unknown: Self = Self(1);
    #[doc(alias = "AEAssessmentErrorUnsupportedPlatform")]
    pub const UnsupportedPlatform: Self = Self(2);
    #[doc(alias = "AEAssessmentErrorMultipleParticipantsNotSupported")]
    pub const MultipleParticipantsNotSupported: Self = Self(3);
    #[doc(alias = "AEAssessmentErrorConfigurationUpdatesNotSupported")]
    pub const ConfigurationUpdatesNotSupported: Self = Self(4);
    #[doc(alias = "AEAssessmentErrorRequiredParticipantsNotAvailable")]
    pub const RequiredParticipantsNotAvailable: Self = Self(5);
}

unsafe impl Encode for AEAssessmentErrorCode {
    const ENCODING: Encoding = NSInteger::ENCODING;
}

unsafe impl RefEncode for AEAssessmentErrorCode {
    const ENCODING_REF: Encoding = Encoding::Pointer(&Self::ENCODING);
}

extern "C" {
    /// [Apple's documentation](https://developer.apple.com/documentation/automaticassessmentconfiguration/aenotinstalledparticipantskey?language=objc)
    pub static AENotInstalledParticipantsKey: &'static NSString;
}

extern "C" {
    /// [Apple's documentation](https://developer.apple.com/documentation/automaticassessmentconfiguration/aerestrictedsystemparticipantskey?language=objc)
    pub static AERestrictedSystemParticipantsKey: &'static NSString;
}
