//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use objc2::__framework_prelude::*;
#[cfg(feature = "objc2-background-assets")]
#[cfg(not(any(target_os = "tvos", target_os = "watchos")))]
use objc2_background_assets::*;

use crate::*;

extern_protocol!(
    /// An application extension that uses the system implementation to schedule Apple-hosted asset-pack downloads automatically.
    ///
    /// You can optionally implement the inherited `BAManagedDownloaderExtension` requirements, but don’t implement any of the inherited `BADownloaderExtension` requirements. For more information, see
    /// <doc
    /// ://com.apple.documentation/documentation/backgroundassets>.
    ///
    /// See also [Apple's documentation](https://developer.apple.com/documentation/storekit/skdownloaderextension?language=objc)
    #[cfg(feature = "objc2-background-assets")]
    #[cfg(not(any(target_os = "tvos", target_os = "watchos")))]
    pub unsafe trait SKDownloaderExtension: BAManagedDownloaderExtension {}
);
