//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::Foundation::*;
use crate::GameController::*;

extern_protocol!(
    pub struct GCDirectionPadElement;

    unsafe impl ProtocolType for GCDirectionPadElement {
        #[method_id(@__retain_semantics Other xAxis)]
        pub unsafe fn xAxis(&self) -> Id<GCAxisInput, Shared>;

        #[method_id(@__retain_semantics Other yAxis)]
        pub unsafe fn yAxis(&self) -> Id<GCAxisInput, Shared>;

        #[method_id(@__retain_semantics Other up)]
        pub unsafe fn up(&self) -> Id<TodoProtocols, Shared>;

        #[method_id(@__retain_semantics Other down)]
        pub unsafe fn down(&self) -> Id<TodoProtocols, Shared>;

        #[method_id(@__retain_semantics Other left)]
        pub unsafe fn left(&self) -> Id<TodoProtocols, Shared>;

        #[method_id(@__retain_semantics Other right)]
        pub unsafe fn right(&self) -> Id<TodoProtocols, Shared>;
    }
);
