//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use core::ffi::*;
use core::ptr::NonNull;
use objc2::__framework_prelude::*;
use objc2_foundation::*;

use crate::*;

/// [Apple's documentation](https://developer.apple.com/documentation/intents/inappendtonoteintentresponsecode?language=objc)
// NS_ENUM
#[deprecated = "INAppendToNoteIntentResponseCode is deprecated. There is no replacement."]
#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, Default)]
pub struct INAppendToNoteIntentResponseCode(pub NSInteger);
impl INAppendToNoteIntentResponseCode {
    /// [Apple's documentation](https://developer.apple.com/documentation/intents/inappendtonoteintentresponsecode/unspecified?language=objc)
    #[doc(alias = "INAppendToNoteIntentResponseCodeUnspecified")]
    #[deprecated = "INAppendToNoteIntentResponseCode is deprecated. There is no replacement."]
    pub const Unspecified: Self = Self(0);
    /// [Apple's documentation](https://developer.apple.com/documentation/intents/inappendtonoteintentresponsecode/ready?language=objc)
    #[doc(alias = "INAppendToNoteIntentResponseCodeReady")]
    #[deprecated = "INAppendToNoteIntentResponseCode is deprecated. There is no replacement."]
    pub const Ready: Self = Self(1);
    /// [Apple's documentation](https://developer.apple.com/documentation/intents/inappendtonoteintentresponsecode/inprogress?language=objc)
    #[doc(alias = "INAppendToNoteIntentResponseCodeInProgress")]
    #[deprecated = "INAppendToNoteIntentResponseCode is deprecated. There is no replacement."]
    pub const InProgress: Self = Self(2);
    /// [Apple's documentation](https://developer.apple.com/documentation/intents/inappendtonoteintentresponsecode/success?language=objc)
    #[doc(alias = "INAppendToNoteIntentResponseCodeSuccess")]
    #[deprecated = "INAppendToNoteIntentResponseCode is deprecated. There is no replacement."]
    pub const Success: Self = Self(3);
    /// [Apple's documentation](https://developer.apple.com/documentation/intents/inappendtonoteintentresponsecode/failure?language=objc)
    #[doc(alias = "INAppendToNoteIntentResponseCodeFailure")]
    #[deprecated = "INAppendToNoteIntentResponseCode is deprecated. There is no replacement."]
    pub const Failure: Self = Self(4);
    /// [Apple's documentation](https://developer.apple.com/documentation/intents/inappendtonoteintentresponsecode/failurerequiringapplaunch?language=objc)
    #[doc(alias = "INAppendToNoteIntentResponseCodeFailureRequiringAppLaunch")]
    #[deprecated = "INAppendToNoteIntentResponseCode is deprecated. There is no replacement."]
    pub const FailureRequiringAppLaunch: Self = Self(5);
    /// [Apple's documentation](https://developer.apple.com/documentation/intents/inappendtonoteintentresponsecode/failurecannotupdatepasswordprotectednote?language=objc)
    #[doc(alias = "INAppendToNoteIntentResponseCodeFailureCannotUpdatePasswordProtectedNote")]
    #[deprecated = "INAppendToNoteIntentResponseCode is deprecated. There is no replacement."]
    pub const FailureCannotUpdatePasswordProtectedNote: Self = Self(6);
}

unsafe impl Encode for INAppendToNoteIntentResponseCode {
    const ENCODING: Encoding = NSInteger::ENCODING;
}

unsafe impl RefEncode for INAppendToNoteIntentResponseCode {
    const ENCODING_REF: Encoding = Encoding::Pointer(&Self::ENCODING);
}

extern_class!(
    /// [Apple's documentation](https://developer.apple.com/documentation/intents/inappendtonoteintentresponse?language=objc)
    #[unsafe(super(INIntentResponse, NSObject))]
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(feature = "INIntentResponse")]
    #[deprecated = "INAppendToNoteIntentResponse is deprecated. There is no replacement."]
    pub struct INAppendToNoteIntentResponse;
);

#[cfg(feature = "INIntentResponse")]
extern_conformance!(
    unsafe impl NSCoding for INAppendToNoteIntentResponse {}
);

#[cfg(feature = "INIntentResponse")]
extern_conformance!(
    unsafe impl NSCopying for INAppendToNoteIntentResponse {}
);

#[cfg(feature = "INIntentResponse")]
unsafe impl CopyingHelper for INAppendToNoteIntentResponse {
    type Result = Self;
}

#[cfg(feature = "INIntentResponse")]
extern_conformance!(
    unsafe impl NSObjectProtocol for INAppendToNoteIntentResponse {}
);

#[cfg(feature = "INIntentResponse")]
extern_conformance!(
    unsafe impl NSSecureCoding for INAppendToNoteIntentResponse {}
);

#[cfg(feature = "INIntentResponse")]
impl INAppendToNoteIntentResponse {
    extern_methods!(
        #[deprecated = "INAppendToNoteIntentResponse is deprecated. There is no replacement."]
        #[unsafe(method(init))]
        #[unsafe(method_family = init)]
        pub unsafe fn init(this: Allocated<Self>) -> Retained<Self>;

        #[deprecated = "INAppendToNoteIntentResponse is deprecated. There is no replacement."]
        #[unsafe(method(initWithCode:userActivity:))]
        #[unsafe(method_family = init)]
        pub unsafe fn initWithCode_userActivity(
            this: Allocated<Self>,
            code: INAppendToNoteIntentResponseCode,
            user_activity: Option<&NSUserActivity>,
        ) -> Retained<Self>;

        #[deprecated = "INAppendToNoteIntentResponse is deprecated. There is no replacement."]
        #[unsafe(method(code))]
        #[unsafe(method_family = none)]
        pub unsafe fn code(&self) -> INAppendToNoteIntentResponseCode;

        #[cfg(feature = "INNote")]
        #[deprecated = "INAppendToNoteIntentResponse is deprecated. There is no replacement."]
        #[unsafe(method(note))]
        #[unsafe(method_family = none)]
        pub unsafe fn note(&self) -> Option<Retained<INNote>>;

        #[cfg(feature = "INNote")]
        /// Setter for [`note`][Self::note].
        ///
        /// This is [copied][objc2_foundation::NSCopying::copy] when set.
        #[deprecated = "INAppendToNoteIntentResponse is deprecated. There is no replacement."]
        #[unsafe(method(setNote:))]
        #[unsafe(method_family = none)]
        pub unsafe fn setNote(&self, note: Option<&INNote>);
    );
}

/// Methods declared on superclass `NSObject`.
#[cfg(feature = "INIntentResponse")]
impl INAppendToNoteIntentResponse {
    extern_methods!(
        #[unsafe(method(new))]
        #[unsafe(method_family = new)]
        pub unsafe fn new() -> Retained<Self>;
    );
}
