//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use core::ptr::NonNull;
use objc2::__framework_prelude::*;
use objc2_foundation::*;

use crate::*;

extern_class!(
    /// A resolution result for an Object associated with an intent.
    ///
    /// ## Overview
    ///
    /// An [`INObjectResolutionResult`](https://developer.apple.com/documentation/intents/inobjectresolutionresult) object is what you return when resolving Object related parameters of an intent object. Use the creation method that best reflects your ability to successfully resolve the parameter.
    ///
    /// For additional resolution options, see [`INIntentResolutionResult`](https://developer.apple.com/documentation/intents/inintentresolutionresult).
    ///
    ///
    #[unsafe(super(INIntentResolutionResult, NSObject))]
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(feature = "INIntentResolutionResult")]
    pub struct INObjectResolutionResult;
);

#[cfg(feature = "INIntentResolutionResult")]
extern_conformance!(
    unsafe impl NSObjectProtocol for INObjectResolutionResult {}
);

#[cfg(feature = "INIntentResolutionResult")]
impl INObjectResolutionResult {
    extern_methods!(
        #[cfg(feature = "INObject")]
        #[unsafe(method(successWithResolvedObject:))]
        #[unsafe(method_family = none)]
        pub unsafe fn successWithResolvedObject(resolved_object: &INObject) -> Retained<Self>;

        #[cfg(feature = "INObject")]
        #[unsafe(method(disambiguationWithObjectsToDisambiguate:))]
        #[unsafe(method_family = none)]
        pub unsafe fn disambiguationWithObjectsToDisambiguate(
            objects_to_disambiguate: &NSArray<INObject>,
        ) -> Retained<Self>;

        #[cfg(feature = "INObject")]
        #[unsafe(method(confirmationRequiredWithObjectToConfirm:))]
        #[unsafe(method_family = none)]
        pub unsafe fn confirmationRequiredWithObjectToConfirm(
            object_to_confirm: Option<&INObject>,
        ) -> Retained<Self>;
    );
}

/// Methods declared on superclass `INIntentResolutionResult`.
#[cfg(feature = "INIntentResolutionResult")]
impl INObjectResolutionResult {
    extern_methods!(
        #[unsafe(method(init))]
        #[unsafe(method_family = init)]
        pub unsafe fn init(this: Allocated<Self>) -> Retained<Self>;

        #[unsafe(method(needsValue))]
        #[unsafe(method_family = none)]
        pub unsafe fn needsValue() -> Retained<Self>;

        #[unsafe(method(notRequired))]
        #[unsafe(method_family = none)]
        pub unsafe fn notRequired() -> Retained<Self>;

        #[unsafe(method(unsupported))]
        #[unsafe(method_family = none)]
        pub unsafe fn unsupported() -> Retained<Self>;
    );
}

/// Methods declared on superclass `NSObject`.
#[cfg(feature = "INIntentResolutionResult")]
impl INObjectResolutionResult {
    extern_methods!(
        #[unsafe(method(new))]
        #[unsafe(method_family = new)]
        pub unsafe fn new() -> Retained<Self>;
    );
}
