//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use core::ptr::NonNull;
use objc2::__framework_prelude::*;
#[cfg(feature = "objc2-core-location")]
use objc2_core_location::*;
use objc2_foundation::*;

use crate::*;

extern_class!(
    /// [Apple's documentation](https://developer.apple.com/documentation/intents/inrentalcarreservation?language=objc)
    #[unsafe(super(INReservation, NSObject))]
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(feature = "INReservation")]
    pub struct INRentalCarReservation;
);

#[cfg(feature = "INReservation")]
extern_conformance!(
    unsafe impl NSCoding for INRentalCarReservation {}
);

#[cfg(feature = "INReservation")]
extern_conformance!(
    unsafe impl NSCopying for INRentalCarReservation {}
);

#[cfg(feature = "INReservation")]
unsafe impl CopyingHelper for INRentalCarReservation {
    type Result = Self;
}

#[cfg(feature = "INReservation")]
extern_conformance!(
    unsafe impl NSObjectProtocol for INRentalCarReservation {}
);

#[cfg(feature = "INReservation")]
extern_conformance!(
    unsafe impl NSSecureCoding for INRentalCarReservation {}
);

#[cfg(feature = "INReservation")]
impl INRentalCarReservation {
    extern_methods!(
        #[cfg(all(
            feature = "INDateComponentsRange",
            feature = "INRentalCar",
            feature = "INReservationAction",
            feature = "INReservationStatus",
            feature = "INSpeakableString",
            feature = "objc2-core-location"
        ))]
        #[unsafe(method(initWithItemReference:reservationNumber:bookingTime:reservationStatus:reservationHolderName:actions:URL:rentalCar:rentalDuration:pickupLocation:dropOffLocation:))]
        #[unsafe(method_family = init)]
        pub unsafe fn initWithItemReference_reservationNumber_bookingTime_reservationStatus_reservationHolderName_actions_URL_rentalCar_rentalDuration_pickupLocation_dropOffLocation(
            this: Allocated<Self>,
            item_reference: &INSpeakableString,
            reservation_number: Option<&NSString>,
            booking_time: Option<&NSDate>,
            reservation_status: INReservationStatus,
            reservation_holder_name: Option<&NSString>,
            actions: Option<&NSArray<INReservationAction>>,
            url: Option<&NSURL>,
            rental_car: &INRentalCar,
            rental_duration: &INDateComponentsRange,
            pickup_location: Option<&CLPlacemark>,
            drop_off_location: Option<&CLPlacemark>,
        ) -> Retained<Self>;

        #[cfg(all(
            feature = "INDateComponentsRange",
            feature = "INRentalCar",
            feature = "INReservationAction",
            feature = "INReservationStatus",
            feature = "INSpeakableString",
            feature = "objc2-core-location"
        ))]
        #[unsafe(method(initWithItemReference:reservationNumber:bookingTime:reservationStatus:reservationHolderName:actions:rentalCar:rentalDuration:pickupLocation:dropOffLocation:))]
        #[unsafe(method_family = init)]
        pub unsafe fn initWithItemReference_reservationNumber_bookingTime_reservationStatus_reservationHolderName_actions_rentalCar_rentalDuration_pickupLocation_dropOffLocation(
            this: Allocated<Self>,
            item_reference: &INSpeakableString,
            reservation_number: Option<&NSString>,
            booking_time: Option<&NSDate>,
            reservation_status: INReservationStatus,
            reservation_holder_name: Option<&NSString>,
            actions: Option<&NSArray<INReservationAction>>,
            rental_car: &INRentalCar,
            rental_duration: &INDateComponentsRange,
            pickup_location: Option<&CLPlacemark>,
            drop_off_location: Option<&CLPlacemark>,
        ) -> Retained<Self>;

        #[cfg(feature = "INRentalCar")]
        #[unsafe(method(rentalCar))]
        #[unsafe(method_family = none)]
        pub unsafe fn rentalCar(&self) -> Retained<INRentalCar>;

        #[cfg(feature = "INDateComponentsRange")]
        #[unsafe(method(rentalDuration))]
        #[unsafe(method_family = none)]
        pub unsafe fn rentalDuration(&self) -> Retained<INDateComponentsRange>;

        #[cfg(feature = "objc2-core-location")]
        #[unsafe(method(pickupLocation))]
        #[unsafe(method_family = none)]
        pub unsafe fn pickupLocation(&self) -> Option<Retained<CLPlacemark>>;

        #[cfg(feature = "objc2-core-location")]
        #[unsafe(method(dropOffLocation))]
        #[unsafe(method_family = none)]
        pub unsafe fn dropOffLocation(&self) -> Option<Retained<CLPlacemark>>;
    );
}

/// Methods declared on superclass `INReservation`.
#[cfg(feature = "INReservation")]
impl INRentalCarReservation {
    extern_methods!(
        #[unsafe(method(init))]
        #[unsafe(method_family = init)]
        pub unsafe fn init(this: Allocated<Self>) -> Retained<Self>;
    );
}

/// Methods declared on superclass `NSObject`.
#[cfg(feature = "INReservation")]
impl INRentalCarReservation {
    extern_methods!(
        #[unsafe(method(new))]
        #[unsafe(method_family = new)]
        pub unsafe fn new() -> Retained<Self>;
    );
}
