//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use core::ptr::NonNull;
use objc2::__framework_prelude::*;

use crate::*;

extern_class!(
    /// [Apple's documentation](https://developer.apple.com/documentation/intents/intaskstatusresolutionresult?language=objc)
    #[unsafe(super(INIntentResolutionResult, NSObject))]
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(feature = "INIntentResolutionResult")]
    #[deprecated = "INTaskStatusResolutionResult is deprecated. Please adopt the Notes or Reminders AppSchema domain instead."]
    pub struct INTaskStatusResolutionResult;
);

#[cfg(feature = "INIntentResolutionResult")]
extern_conformance!(
    unsafe impl NSObjectProtocol for INTaskStatusResolutionResult {}
);

#[cfg(feature = "INIntentResolutionResult")]
impl INTaskStatusResolutionResult {
    extern_methods!(
        #[cfg(feature = "INTaskStatus")]
        #[deprecated = "INTaskStatusResolutionResult is deprecated. Please adopt the Notes or Reminders AppSchema domain instead."]
        #[unsafe(method(successWithResolvedTaskStatus:))]
        #[unsafe(method_family = none)]
        pub unsafe fn successWithResolvedTaskStatus(
            resolved_task_status: INTaskStatus,
        ) -> Retained<Self>;

        #[cfg(feature = "INTaskStatus")]
        #[deprecated = "INTaskStatusResolutionResult is deprecated. Please adopt the Notes or Reminders AppSchema domain instead."]
        #[unsafe(method(confirmationRequiredWithTaskStatusToConfirm:))]
        #[unsafe(method_family = none)]
        pub unsafe fn confirmationRequiredWithTaskStatusToConfirm(
            task_status_to_confirm: INTaskStatus,
        ) -> Retained<Self>;
    );
}

/// Methods declared on superclass `INIntentResolutionResult`.
#[cfg(feature = "INIntentResolutionResult")]
impl INTaskStatusResolutionResult {
    extern_methods!(
        // -init (unavailable)

        #[unsafe(method(needsValue))]
        #[unsafe(method_family = none)]
        pub unsafe fn needsValue() -> Retained<Self>;

        #[unsafe(method(notRequired))]
        #[unsafe(method_family = none)]
        pub unsafe fn notRequired() -> Retained<Self>;

        #[unsafe(method(unsupported))]
        #[unsafe(method_family = none)]
        pub unsafe fn unsupported() -> Retained<Self>;
    );
}

/// Methods declared on superclass `NSObject`.
#[cfg(feature = "INIntentResolutionResult")]
impl INTaskStatusResolutionResult {
    extern_methods!(
        // +new (unavailable)

    );
}
